# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

module Pangea
  module Resources
    module Datadog
      include DatadogMonitor
      include DatadogDashboard
      include DatadogDashboardJson
      include DatadogSyntheticsTest
      include DatadogServiceLevelObjective
      include DatadogLogsIndex
      include DatadogLogsPipeline
      include DatadogLogsMetric
      include DatadogApmRetentionFilter
      include DatadogIntegrationAws
    end
  end
end
