# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class LogsMetricAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :compute, T::Hash
    attribute :filter, T::Hash
    attribute :name, T::String
    attribute? :group_by, T::Array.of(T::Hash).optional
  end
end
