# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class CustomAllocationRulesAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :rule_ids, T::Array.of(T::String)
    attribute? :override_ui_defined_resources, T::Bool.optional
  end
end
