# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_deployment_gate/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogDeploymentGate
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_deployment_gate,
      attributes_class: Datadog::Types::DeploymentGateAttributes,
      outputs: { id: :id },
      map: [:env, :service],
      map_present: [:identifier, :rule],
      map_bool: [:dry_run]
  end
  module Datadog
    include DatadogDeploymentGate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
