# Code generated by pangea-forge.
# InSpec profile for verifying datadog_integration_gcp infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_integration_gcp/ -t datadog://

control 'datadog_integration_gcp-exists' do
  impact 1.0
  title 'Manages a datadog_integration_gcp resource'
  desc 'Verify that the datadog_integration_gcp resource exists and has expected properties'

  describe datadog_integration_gcp(name: attribute('id')) do
    it { should exist }
    its('client_email') { should_not be_nil }
    its('client_id') { should_not be_nil }
    its('private_key_id') { should_not be_nil }
    its('project_id') { should_not be_nil }
  end
end
