# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class ApmRetentionFilterAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :enabled, T::Bool
    attribute :filter_type, T::String
    attribute :name, T::String
    attribute :rate, T::String
    attribute? :filter, T::Hash.optional
    attribute? :trace_rate, T::String.optional
  end
end
