# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_agentless_scanning_aws_scan_options/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogAgentlessScanningAwsScanOptions
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_agentless_scanning_aws_scan_options,
      attributes_class: Datadog::Types::AgentlessScanningAwsScanOptionsAttributes,
      outputs: { id: :id },
      map: [:aws_account_id],
      map_bool: [:lambda, :sensitive_data, :vuln_containers_os, :vuln_host_os]
  end
  module Datadog
    include DatadogAgentlessScanningAwsScanOptions
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
