# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class AgentlessScanningAwsScanOptionsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :aws_account_id, T::String
    attribute :lambda, T::Bool
    attribute :sensitive_data, T::Bool
    attribute :vuln_containers_os, T::Bool
    attribute :vuln_host_os, T::Bool
  end
end
