# Code generated by pangea-forge.
# InSpec profile for verifying datadog_gcp_uc_config infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_gcp_uc_config/ -t datadog://

control 'datadog_gcp_uc_config-exists' do
  impact 1.0
  title 'Manages a datadog_gcp_uc_config resource'
  desc 'Verify that the datadog_gcp_uc_config resource exists and has expected properties'

  describe datadog_gcp_uc_config(name: attribute('id')) do
    it { should exist }
    its('billing_account_id') { should_not be_nil }
    its('bucket_name') { should_not be_nil }
    its('export_dataset_name') { should_not be_nil }
    its('export_project_name') { should_not be_nil }
    its('service_account') { should_not be_nil }
  end
end
