# Code generated by pangea-forge.
# InSpec profile for verifying datadog_synthetics_test infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_synthetics_test/ -t datadog://

control 'datadog_synthetics_test-exists' do
  impact 1.0
  title 'Manages a datadog_synthetics_test resource'
  desc 'Verify that the datadog_synthetics_test resource exists and has expected properties'

  describe datadog_synthetics_test(name: attribute('id')) do
    it { should exist }
    its('locations') { should_not be_nil }
    its('name') { should_not be_nil }
    its('status') { should_not be_nil }
    its('type') { should_not be_nil }
  end
end
