# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_integration_pagerduty/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogIntegrationPagerduty
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_integration_pagerduty,
      attributes_class: Datadog::Types::IntegrationPagerdutyAttributes,
      outputs: { id: :id },
      map: [:subdomain],
      map_present: [:api_token, :schedules]
  end
  module Datadog
    include DatadogIntegrationPagerduty
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
