# Code generated by pangea-forge.
# InSpec profile for verifying datadog_security_monitoring_critical_asset infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_security_monitoring_critical_asset/ -t datadog://

control 'datadog_security_monitoring_critical_asset-exists' do
  impact 1.0
  title 'Manages a datadog_security_monitoring_critical_asset resource'
  desc 'Verify that the datadog_security_monitoring_critical_asset resource exists and has expected properties'

  describe datadog_security_monitoring_critical_asset(name: attribute('id')) do
    it { should exist }
    its('query') { should_not be_nil }
    its('rule_query') { should_not be_nil }
    its('severity') { should_not be_nil }
  end
end
