# Code generated by pangea-forge.
# InSpec profile for verifying datadog_logs_pipeline_order infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_logs_pipeline_order/ -t datadog://

control 'datadog_logs_pipeline_order-exists' do
  impact 1.0
  title 'Manages a datadog_logs_pipeline_order resource'
  desc 'Verify that the datadog_logs_pipeline_order resource exists and has expected properties'

  describe datadog_logs_pipeline_order(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('pipelines') { should_not be_nil }
  end
end
