# Code generated by pangea-forge.
# InSpec profile for verifying datadog_logs_metric infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_logs_metric/ -t datadog://

control 'datadog_logs_metric-exists' do
  impact 1.0
  title 'Manages a datadog_logs_metric resource'
  desc 'Verify that the datadog_logs_metric resource exists and has expected properties'

  describe datadog_logs_metric(name: attribute('id')) do
    it { should exist }
    its('compute') { should_not be_nil }
    its('filter') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
