# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_logs_pipeline/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogLogsPipeline
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_logs_pipeline,
      attributes_class: Datadog::Types::LogsPipelineAttributes,
      outputs: { id: :id, name: :name },
      map: [:name, :filter],
      map_present: [:processors],
      map_bool: [:is_enabled]
  end
  module Datadog
    include DatadogLogsPipeline
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
