# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/datadog_types'

module Pangea::Resources::Datadog::Types
  class LogsPipelineAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Datadog::Types

    attribute :filter, T::String
    attribute? :is_enabled, T::Bool.optional
    attribute :name, T::String
    attribute? :processors, T::String.optional
  end
end
