# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class SyntheticsPrivateLocationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :name, T::String
    attribute? :api_key, T::String.optional
    attribute? :description, T::String.optional
    attribute? :metadata, T::Array.of(T::Hash).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
