# Code generated by pangea-forge.
# InSpec profile for verifying datadog_dashboard_json infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_dashboard_json/ -t datadog://

control 'datadog_dashboard_json-exists' do
  impact 1.0
  title 'Manages a datadog_dashboard_json resource'
  desc 'Verify that the datadog_dashboard_json resource exists and has expected properties'

  describe datadog_dashboard_json(name: attribute('id')) do
    it { should exist }
    its('dashboard') { should_not be_nil }
  end
end
