# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_cloud_inventory_sync_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogCloudInventorySyncConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_cloud_inventory_sync_config,
      attributes_class: Datadog::Types::CloudInventorySyncConfigAttributes,
      outputs: { id: :id },
      map: [:cloud_provider],
      map_present: [:aws, :azure, :gcp]
  end
  module Datadog
    include DatadogCloudInventorySyncConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
