# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class CloudInventorySyncConfigAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :cloud_provider, T::String
    attribute? :aws, T::Hash.optional
    attribute? :azure, T::Hash.optional
    attribute? :gcp, T::Hash.optional
  end
end
