# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_appsec_waf_custom_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogAppsecWafCustomRule
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_appsec_waf_custom_rule,
      attributes_class: Datadog::Types::AppsecWafCustomRuleAttributes,
      outputs: { id: :id },
      map: [:name, :tags],
      map_present: [:action, :condition, :path_glob, :scope],
      map_bool: [:blocking, :enabled]
  end
  module Datadog
    include DatadogAppsecWafCustomRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
