# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_integration_ms_teams_tenant_based_handle/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogIntegrationMsTeamsTenantBasedHandle
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_integration_ms_teams_tenant_based_handle,
      attributes_class: Datadog::Types::IntegrationMsTeamsTenantBasedHandleAttributes,
      outputs: { id: :id },
      map: [:channel_name, :name, :team_name, :tenant_name]
  end
  module Datadog
    include DatadogIntegrationMsTeamsTenantBasedHandle
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
