# Code generated by pangea-forge.
# InSpec profile for verifying datadog_appsec_waf_custom_rule infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_appsec_waf_custom_rule/ -t datadog://

control 'datadog_appsec_waf_custom_rule-exists' do
  impact 1.0
  title 'Manages a datadog_appsec_waf_custom_rule resource'
  desc 'Verify that the datadog_appsec_waf_custom_rule resource exists and has expected properties'

  describe datadog_appsec_waf_custom_rule(name: attribute('id')) do
    it { should exist }
    its('blocking') { should_not be_nil }
    its('enabled') { should_not be_nil }
    its('name') { should_not be_nil }
    its('tags') { should_not be_nil }
  end
end
