# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_service_level_objective/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogServiceLevelObjective
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_service_level_objective,
      attributes_class: Datadog::Types::ServiceLevelObjectiveAttributes,
      outputs: { id: :id },
      map: [:name, :thresholds, :type],
      map_present: [:description, :groups, :monitor_ids, :query, :sli_specification, :tags, :target_threshold, :timeframe, :warning_threshold],
      map_bool: [:force_delete, :validate]
  end
  module Datadog
    include DatadogServiceLevelObjective
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
