# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class ServiceLevelObjectiveAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :name, T::String
    attribute :thresholds, T::Array.of(T::Hash)
    attribute :type, T::String
    attribute? :description, T::String.optional
    attribute? :force_delete, T::Bool.optional
    attribute? :groups, T::Array.of(T::String).optional
    attribute? :monitor_ids, T::Array.of((T::Coercible::Integer | T::Coercible::Float)).optional
    attribute? :query, T::Hash.optional
    attribute? :sli_specification, T::Hash.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :target_threshold, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :timeframe, T::String.optional
    attribute? :validate, T::Bool.optional
    attribute? :warning_threshold, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
