# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_cloud_workload_security_agent_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogCloudWorkloadSecurityAgentRule
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_cloud_workload_security_agent_rule,
      attributes_class: Datadog::Types::CloudWorkloadSecurityAgentRuleAttributes,
      outputs: { id: :id },
      map: [:expression, :name],
      map_present: [:description],
      map_bool: [:enabled]
  end
  module Datadog
    include DatadogCloudWorkloadSecurityAgentRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
