# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class CloudWorkloadSecurityAgentRuleAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :expression, T::String
    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :enabled, T::Bool.optional
  end
end
