# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_compliance_custom_framework/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogComplianceCustomFramework
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_compliance_custom_framework,
      attributes_class: Datadog::Types::ComplianceCustomFrameworkAttributes,
      outputs: { id: :id },
      map: [:handle, :name, :version],
      map_present: [:icon_url, :requirements]
  end
  module Datadog
    include DatadogComplianceCustomFramework
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
