# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class ComplianceCustomFrameworkAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :handle, T::String
    attribute :name, T::String
    attribute :version, T::String
    attribute? :icon_url, T::String.optional
    attribute? :requirements, T::Array.of(T::Hash).optional
  end
end
