# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogRole
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_role,
      attributes_class: Datadog::Types::RoleAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:permission],
      map_bool: [:default_permissions_opt_out, :validate]
  end
  module Datadog
    include DatadogRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
