# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class CsmThreatsPolicyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :enabled, T::Bool.optional
    attribute? :host_tags_lists, T::Array.of(T::Array.of(T::String)).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
