# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_security_monitoring_filter/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSecurityMonitoringFilter
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_security_monitoring_filter,
      attributes_class: Datadog::Types::SecurityMonitoringFilterAttributes,
      outputs: { id: :id },
      map: [:name, :query],
      map_present: [:exclusion_filter, :filtered_data_type],
      map_bool: [:is_enabled]
  end
  module Datadog
    include DatadogSecurityMonitoringFilter
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
