# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class CloudConfigurationRuleAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :enabled, T::Bool
    attribute :message, T::String
    attribute :name, T::String
    attribute :policy, (T::String | T::Hash)
    attribute :resource_type, T::String
    attribute :severity, T::String
    attribute? :filter, T::Array.of(T::Hash).optional
    attribute? :group_by, T::Array.of(T::String).optional
    attribute? :notifications, T::Array.of(T::String).optional
    attribute? :related_resource_types, T::Array.of(T::String).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
