# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_synthetics_suite/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSyntheticsSuite
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_synthetics_suite,
      attributes_class: Datadog::Types::SyntheticsSuiteAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:message, :options, :tags, :tests]
  end
  module Datadog
    include DatadogSyntheticsSuite
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
