# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class SyntheticsSuiteAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :name, T::String
    attribute? :message, T::String.optional
    attribute? :options, T::Array.of(T::Hash).optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :tests, T::Array.of(T::Hash).optional
  end
end
