# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class CustomAllocationRuleAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :enabled, T::Bool
    attribute :providernames, T::Array.of(T::String)
    attribute :rule_name, T::String
    attribute? :costs_to_allocate, T::Array.of(T::Hash).optional
    attribute? :strategy, T::Hash.optional
  end
end
