# Code generated by pangea-forge.
# InSpec profile for verifying datadog_powerpack infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_powerpack/ -t datadog://

control 'datadog_powerpack-exists' do
  impact 1.0
  title 'Manages a datadog_powerpack resource'
  desc 'Verify that the datadog_powerpack resource exists and has expected properties'

  describe datadog_powerpack(name: attribute('id')) do
    it { should exist }
  end
end
