# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_on_call_team_routing_rules/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogOnCallTeamRoutingRules
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_on_call_team_routing_rules,
      attributes_class: Datadog::Types::OnCallTeamRoutingRulesAttributes,
      outputs: { id: :id },
      map: [:id],
      map_present: [:rule]
  end
  module Datadog
    include DatadogOnCallTeamRoutingRules
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
