# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class SyntheticsGlobalVariableAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :is_fido, T::Bool.optional
    attribute? :is_totp, T::Bool.optional
    attribute? :options, T::Array.of(T::Hash).optional
    attribute? :parse_test_id, T::String.optional
    attribute? :parse_test_options, T::Array.of(T::Hash).optional
    attribute? :restricted_roles, T::Array.of(T::String).optional
    attribute? :secure, T::Bool.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :value, T::String.optional
    attribute? :value_wo, T::String.optional
    attribute? :value_wo_version, T::String.optional
  end
end
