# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_secure_embed_dashboard/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSecureEmbedDashboard
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_secure_embed_dashboard,
      attributes_class: Datadog::Types::SecureEmbedDashboardAttributes,
      outputs: { id: :id },
      map: [:dashboard_id, :title],
      map_present: [:global_time_live_span, :selectable_template_vars, :status, :viewing_preferences_theme],
      map_bool: [:global_time_selectable, :viewing_preferences_high_density]
  end
  module Datadog
    include DatadogSecureEmbedDashboard
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
