# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class SecureEmbedDashboardAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :dashboard_id, T::String
    attribute :title, T::String
    attribute? :global_time_live_span, T::String.optional
    attribute? :global_time_selectable, T::Bool.optional
    attribute? :selectable_template_vars, T::Array.of(T::Hash).optional
    attribute? :status, T::String.optional
    attribute? :viewing_preferences_high_density, T::Bool.optional
    attribute? :viewing_preferences_theme, T::String.optional
  end
end
