# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class IntegrationConfluentResourceAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :account_id, T::String
    attribute :resource_id, T::String
    attribute? :enable_custom_metrics, T::Bool.optional
    attribute? :resource_type, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
