# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_azure_uc_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogAzureUcConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_azure_uc_config,
      attributes_class: Datadog::Types::AzureUcConfigAttributes,
      outputs: { id: :id },
      map: [:account_id, :client_id, :scope],
      map_present: [:actual_bill_config, :amortized_bill_config]
  end
  module Datadog
    include DatadogAzureUcConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
