# Code generated by pangea-forge.
# InSpec profile for verifying datadog_tag_pipeline_ruleset infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_tag_pipeline_ruleset/ -t datadog://

control 'datadog_tag_pipeline_ruleset-exists' do
  impact 1.0
  title 'Manages a datadog_tag_pipeline_ruleset resource'
  desc 'Verify that the datadog_tag_pipeline_ruleset resource exists and has expected properties'

  describe datadog_tag_pipeline_ruleset(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
