# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_sensitive_data_scanner_group_order/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSensitiveDataScannerGroupOrder
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_sensitive_data_scanner_group_order,
      attributes_class: Datadog::Types::SensitiveDataScannerGroupOrderAttributes,
      outputs: { id: :id },
      map: [:group_ids]
  end
  module Datadog
    include DatadogSensitiveDataScannerGroupOrder
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
