# Code generated by pangea-forge.
# InSpec profile for verifying datadog_downtime_schedule infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_downtime_schedule/ -t datadog://

control 'datadog_downtime_schedule-exists' do
  impact 1.0
  title 'Manages a datadog_downtime_schedule resource'
  desc 'Verify that the datadog_downtime_schedule resource exists and has expected properties'

  describe datadog_downtime_schedule(name: attribute('id')) do
    it { should exist }
    its('scope') { should_not be_nil }
  end
end
