# Code generated by pangea-forge.
# InSpec profile for verifying datadog_agentless_scanning_aws_scan_options infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_agentless_scanning_aws_scan_options/ -t datadog://

control 'datadog_agentless_scanning_aws_scan_options-exists' do
  impact 1.0
  title 'Manages a datadog_agentless_scanning_aws_scan_options resource'
  desc 'Verify that the datadog_agentless_scanning_aws_scan_options resource exists and has expected properties'

  describe datadog_agentless_scanning_aws_scan_options(name: attribute('id')) do
    it { should exist }
    its('aws_account_id') { should_not be_nil }
    its('lambda') { should_not be_nil }
    its('sensitive_data') { should_not be_nil }
    its('vuln_containers_os') { should_not be_nil }
    its('vuln_host_os') { should_not be_nil }
  end
end
