# Code generated by pangea-forge.
# InSpec profile for verifying datadog_team_membership infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_team_membership/ -t datadog://

control 'datadog_team_membership-exists' do
  impact 1.0
  title 'Manages a datadog_team_membership resource'
  desc 'Verify that the datadog_team_membership resource exists and has expected properties'

  describe datadog_team_membership(name: attribute('id')) do
    it { should exist }
    its('team_id') { should_not be_nil }
    its('user_id') { should_not be_nil }
  end
end
