# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_logs_integration_pipeline/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogLogsIntegrationPipeline
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_logs_integration_pipeline,
      attributes_class: Datadog::Types::LogsIntegrationPipelineAttributes,
      outputs: { id: :id },
      map_bool: [:is_enabled]
  end
  module Datadog
    include DatadogLogsIntegrationPipeline
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
