# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_security_notification_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSecurityNotificationRule
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_security_notification_rule,
      attributes_class: Datadog::Types::SecurityNotificationRuleAttributes,
      outputs: { id: :id },
      map: [:name, :targets],
      map_present: [:selectors, :time_aggregation],
      map_bool: [:enabled]
  end
  module Datadog
    include DatadogSecurityNotificationRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
