# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class SecurityMonitoringDefaultRuleAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute? :case, T::Array.of(T::Hash).optional
    attribute? :custom_message, T::String.optional
    attribute? :custom_name, T::String.optional
    attribute? :custom_tags, T::Array.of(T::String).optional
    attribute? :enabled, T::Bool.optional
    attribute? :filter, T::Array.of(T::Hash).optional
    attribute? :options, T::Hash.optional
    attribute? :query, T::Array.of(T::Hash).optional
  end
end
