# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_rum_application/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogRumApplication
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_rum_application,
      attributes_class: Datadog::Types::RumApplicationAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:product_analytics_retention_state, :rum_event_processing_state, :type]
  end
  module Datadog
    include DatadogRumApplication
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
