# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_slo_correction/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSloCorrection
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_slo_correction,
      attributes_class: Datadog::Types::SloCorrectionAttributes,
      outputs: { id: :id },
      map: [:category, :slo_id, :start],
      map_present: [:description, :duration, :end, :rrule, :timezone]
  end
  module Datadog
    include DatadogSloCorrection
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
