# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_organization_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogOrganizationSettings
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_organization_settings,
      attributes_class: Datadog::Types::OrganizationSettingsAttributes,
      outputs: { id: :id },
      map_present: [:name, :security_contacts, :settings]
  end
  module Datadog
    include DatadogOrganizationSettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
