# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class OrganizationSettingsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute? :name, T::String.optional
    attribute? :security_contacts, T::Array.of(T::String).optional
    attribute? :settings, T::Hash.optional
  end
end
