# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_rum_retention_filters_order/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogRumRetentionFiltersOrder
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_rum_retention_filters_order,
      attributes_class: Datadog::Types::RumRetentionFiltersOrderAttributes,
      outputs: { id: :id },
      map: [:application_id, :retention_filter_ids]
  end
  module Datadog
    include DatadogRumRetentionFiltersOrder
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
