# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class IntegrationGcpAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :client_email, T::String
    attribute :client_id, T::String
    attribute :private_key, T::String
    attribute :private_key_id, T::String
    attribute :project_id, T::String
    attribute? :automute, T::Bool.optional
    attribute? :cloud_run_revision_filters, T::Array.of(T::String).optional
    attribute? :cspm_resource_collection_enabled, T::Bool.optional
    attribute? :host_filters, T::String.optional
    attribute? :is_resource_change_collection_enabled, T::Bool.optional
    attribute? :is_security_command_center_enabled, T::Bool.optional
    attribute? :monitored_resource_configs, T::Array.of(T::Hash).optional
    attribute? :resource_collection_enabled, T::Bool.optional
  end
end
