# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogUser
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_user,
      attributes_class: Datadog::Types::UserAttributes,
      outputs: { id: :id },
      map: [:email],
      map_present: [:name, :roles],
      map_bool: [:disabled, :send_user_invitation]
  end
  module Datadog
    include DatadogUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
