# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_synthetics_concurrency_cap/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSyntheticsConcurrencyCap
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_synthetics_concurrency_cap,
      attributes_class: Datadog::Types::SyntheticsConcurrencyCapAttributes,
      outputs: { id: :id },
      map: [:on_demand_concurrency_cap]
  end
  module Datadog
    include DatadogSyntheticsConcurrencyCap
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
