# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class SyntheticsConcurrencyCapAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :on_demand_concurrency_cap, (T::Coercible::Integer | T::Coercible::Float)
  end
end
