# Code generated by pangea-forge.
# InSpec profile for verifying datadog_restriction_policy infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_restriction_policy/ -t datadog://

control 'datadog_restriction_policy-exists' do
  impact 1.0
  title 'Manages a datadog_restriction_policy resource'
  desc 'Verify that the datadog_restriction_policy resource exists and has expected properties'

  describe datadog_restriction_policy(name: attribute('id')) do
    it { should exist }
    its('resource_id') { should_not be_nil }
  end
end
