# Code generated by pangea-forge.
# InSpec profile for verifying datadog_downtime infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_downtime/ -t datadog://

control 'datadog_downtime-exists' do
  impact 1.0
  title 'Manages a datadog_downtime resource'
  desc 'Verify that the datadog_downtime resource exists and has expected properties'

  describe datadog_downtime(name: attribute('id')) do
    it { should exist }
    its('scope') { should_not be_nil }
  end
end
