# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_child_organization/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogChildOrganization
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_child_organization,
      attributes_class: Datadog::Types::ChildOrganizationAttributes,
      outputs: { id: :id },
      map: [:name]
  end
  module Datadog
    include DatadogChildOrganization
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
