# Code generated by pangea-forge.
# InSpec profile for verifying datadog_synthetics_concurrency_cap infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_synthetics_concurrency_cap/ -t datadog://

control 'datadog_synthetics_concurrency_cap-exists' do
  impact 1.0
  title 'Manages a datadog_synthetics_concurrency_cap resource'
  desc 'Verify that the datadog_synthetics_concurrency_cap resource exists and has expected properties'

  describe datadog_synthetics_concurrency_cap(name: attribute('id')) do
    it { should exist }
    its('on_demand_concurrency_cap') { should_not be_nil }
  end
end
