# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_team_notification_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogTeamNotificationRule
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_team_notification_rule,
      attributes_class: Datadog::Types::TeamNotificationRuleAttributes,
      outputs: { id: :id },
      map: [:team_id],
      map_present: [:email, :ms_teams, :pagerduty, :slack]
  end
  module Datadog
    include DatadogTeamNotificationRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
