# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_integration_gcp_sts/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogIntegrationGcpSts
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_integration_gcp_sts,
      attributes_class: Datadog::Types::IntegrationGcpStsAttributes,
      outputs: { id: :id },
      map: [:client_email],
      map_present: [:account_tags, :cloud_run_revision_filters, :host_filters, :metric_namespace_configs, :monitored_resource_configs, :region_filter_configs],
      map_bool: [:automute, :is_cspm_enabled, :is_global_location_enabled, :is_per_project_quota_enabled, :is_resource_change_collection_enabled, :is_security_command_center_enabled, :resource_collection_enabled]
  end
  module Datadog
    include DatadogIntegrationGcpSts
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
