# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_reference_table/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogReferenceTable
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_reference_table,
      attributes_class: Datadog::Types::ReferenceTableAttributes,
      outputs: { id: :id },
      map: [:source, :table_name],
      map_present: [:description, :file_metadata, :schema, :tags]
  end
  module Datadog
    include DatadogReferenceTable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
