# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_software_catalog/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSoftwareCatalog
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_software_catalog,
      attributes_class: Datadog::Types::SoftwareCatalogAttributes,
      outputs: { id: :id },
      map: [:entity]
  end
  module Datadog
    include DatadogSoftwareCatalog
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
