# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class IntegrationFastlyServiceAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :service_id, T::String
    attribute? :account_id, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
