# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_user_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogUserRole
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_user_role,
      attributes_class: Datadog::Types::UserRoleAttributes,
      outputs: { id: :id },
      map: [:role_id, :user_id]
  end
  module Datadog
    include DatadogUserRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
