# Code generated by pangea-forge.
# InSpec profile for verifying datadog_secure_embed_dashboard infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_secure_embed_dashboard/ -t datadog://

control 'datadog_secure_embed_dashboard-exists' do
  impact 1.0
  title 'Manages a datadog_secure_embed_dashboard resource'
  desc 'Verify that the datadog_secure_embed_dashboard resource exists and has expected properties'

  describe datadog_secure_embed_dashboard(name: attribute('id')) do
    it { should exist }
    its('dashboard_id') { should_not be_nil }
    its('title') { should_not be_nil }
  end
end
