# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_dashboard/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogDashboard
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_dashboard,
      attributes_class: Datadog::Types::DashboardAttributes,
      outputs: { id: :id, url: :url },
      map: [:title, :layout_type],
      map_present: [:description, :notify_list, :reflow_type, :tags, :template_variables, :widgets],
      map_bool: [:is_read_only]
  end
  module Datadog
    include DatadogDashboard
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
