# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/datadog_types'

module Pangea::Resources::Datadog::Types
  class DashboardAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Datadog::Types

    attribute? :description, T::String.optional
    attribute? :is_read_only, T::Bool.optional
    attribute :layout_type, T::String
    attribute? :notify_list, T::Array.of(T::String).optional
    attribute? :reflow_type, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :template_variables, T::Array.of(T::String).optional
    attribute :title, T::String
    attribute? :widgets, T::String.optional
  end
end
