# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_dashboard_list/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogDashboardList
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_dashboard_list,
      attributes_class: Datadog::Types::DashboardListAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:dash_item]
  end
  module Datadog
    include DatadogDashboardList
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
