# Code generated by pangea-forge.
# InSpec profile for verifying datadog_metric_metadata infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_metric_metadata/ -t datadog://

control 'datadog_metric_metadata-exists' do
  impact 1.0
  title 'Manages a datadog_metric_metadata resource'
  desc 'Verify that the datadog_metric_metadata resource exists and has expected properties'

  describe datadog_metric_metadata(name: attribute('id')) do
    it { should exist }
    its('metric') { should_not be_nil }
  end
end
