# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_sensitive_data_scanner_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSensitiveDataScannerRule
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_sensitive_data_scanner_rule,
      attributes_class: Datadog::Types::SensitiveDataScannerRuleAttributes,
      outputs: { id: :id },
      map: [:group_id],
      map_present: [:description, :excluded_namespaces, :included_keyword_configuration, :name, :namespaces, :pattern, :priority, :standard_pattern_id, :tags, :text_replacement],
      map_bool: [:is_enabled]
  end
  module Datadog
    include DatadogSensitiveDataScannerRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
