# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_service_definition_yaml/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogServiceDefinitionYaml
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_service_definition_yaml,
      attributes_class: Datadog::Types::ServiceDefinitionYamlAttributes,
      outputs: { id: :id },
      map: [:service_definition]
  end
  module Datadog
    include DatadogServiceDefinitionYaml
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
