# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class TeamLinkAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :label, T::String
    attribute :team_id, T::String
    attribute :url, T::String
    attribute? :position, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
