# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class IntegrationCloudflareAccountAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :api_key, T::String
    attribute :name, T::String
    attribute? :email, T::String.optional
    attribute? :resources, T::Array.of(T::String).optional
  end
end
