# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_restriction_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogRestrictionPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_restriction_policy,
      attributes_class: Datadog::Types::RestrictionPolicyAttributes,
      outputs: { id: :id },
      map: [:resource_id],
      map_present: [:bindings]
  end
  module Datadog
    include DatadogRestrictionPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
