# Code generated by pangea-forge.
# InSpec profile for verifying datadog_workflow_automation infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_workflow_automation/ -t datadog://

control 'datadog_workflow_automation-exists' do
  impact 1.0
  title 'Manages a datadog_workflow_automation resource'
  desc 'Verify that the datadog_workflow_automation resource exists and has expected properties'

  describe datadog_workflow_automation(name: attribute('id')) do
    it { should exist }
    its('description') { should_not be_nil }
    its('name') { should_not be_nil }
    its('published') { should_not be_nil }
    its('spec_json') { should_not be_nil }
    its('tags') { should_not be_nil }
  end
end
