# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea-core'
require 'terraform-synthesizer'

# Datadog types
require_relative 'pangea/types/datadog_types'

# Datadog resources
require_relative 'pangea/resources/datadog_monitor/resource'
require_relative 'pangea/resources/datadog_dashboard/resource'
require_relative 'pangea/resources/datadog_dashboard_json/resource'
require_relative 'pangea/resources/datadog_synthetics_test/resource'
require_relative 'pangea/resources/datadog_service_level_objective/resource'
require_relative 'pangea/resources/datadog_logs_index/resource'
require_relative 'pangea/resources/datadog_logs_pipeline/resource'
require_relative 'pangea/resources/datadog_logs_metric/resource'
require_relative 'pangea/resources/datadog_apm_retention_filter/resource'
require_relative 'pangea/resources/datadog_integration_aws/resource'

# Datadog module aggregator
require_relative 'pangea/resources/datadog'
