# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_spans_metric/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSpansMetric
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_spans_metric,
      attributes_class: Datadog::Types::SpansMetricAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:compute, :filter, :group_by]
  end
  module Datadog
    include DatadogSpansMetric
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
