# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class MonitorAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :message, T::String
    attribute :name, T::String
    attribute :query, T::String
    attribute :type, T::String
    attribute? :assets, T::Array.of(T::Hash).optional
    attribute? :draft_status, T::String.optional
    attribute? :enable_logs_sample, T::Bool.optional
    attribute? :enable_samples, T::Bool.optional
    attribute? :escalation_message, T::String.optional
    attribute? :evaluation_delay, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :force_delete, T::Bool.optional
    attribute? :group_retention_duration, T::String.optional
    attribute? :groupby_simple_monitor, T::Bool.optional
    attribute? :include_tags, T::Bool.optional
    attribute? :monitor_threshold_windows, T::Hash.optional
    attribute? :monitor_thresholds, T::Hash.optional
    attribute? :new_group_delay, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :new_host_delay, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :no_data_timeframe, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :notification_preset_name, T::String.optional
    attribute? :notify_audit, T::Bool.optional
    attribute? :notify_by, T::Array.of(T::String).optional
    attribute? :notify_no_data, T::Bool.optional
    attribute? :on_missing_data, T::String.optional
    attribute? :priority, T::String.optional
    attribute? :renotify_interval, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :renotify_occurrences, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :renotify_statuses, T::Array.of(T::String).optional
    attribute? :require_full_window, T::Bool.optional
    attribute? :restricted_roles, T::Array.of(T::String).optional
    attribute? :scheduling_options, T::Hash.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :timeout_h, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :validate, T::Bool.optional
    attribute? :variables, T::Hash.optional
  end
end
