# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_tag_pipeline_ruleset/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogTagPipelineRuleset
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_tag_pipeline_ruleset,
      attributes_class: Datadog::Types::TagPipelineRulesetAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:rules],
      map_bool: [:enabled]
  end
  module Datadog
    include DatadogTagPipelineRuleset
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
