# Code generated by pangea-forge.
# InSpec profile for verifying datadog_on_call_user_notification_rule infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_on_call_user_notification_rule/ -t datadog://

control 'datadog_on_call_user_notification_rule-exists' do
  impact 1.0
  title 'Manages a datadog_on_call_user_notification_rule resource'
  desc 'Verify that the datadog_on_call_user_notification_rule resource exists and has expected properties'

  describe datadog_on_call_user_notification_rule(name: attribute('id')) do
    it { should exist }
    its('category') { should_not be_nil }
    its('channel_id') { should_not be_nil }
    its('delay_minutes') { should_not be_nil }
    its('user_id') { should_not be_nil }
  end
end
