# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_service_account/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogServiceAccount
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_service_account,
      attributes_class: Datadog::Types::ServiceAccountAttributes,
      outputs: { id: :id },
      map: [:email],
      map_present: [:name, :roles],
      map_bool: [:disabled]
  end
  module Datadog
    include DatadogServiceAccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
