# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class ServiceAccountAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :email, T::String
    attribute? :disabled, T::Bool.optional
    attribute? :name, T::String.optional
    attribute? :roles, T::Array.of(T::String).optional
  end
end
