# Code generated by pangea-forge.
# InSpec profile for verifying datadog_team_permission_setting infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_team_permission_setting/ -t datadog://

control 'datadog_team_permission_setting-exists' do
  impact 1.0
  title 'Manages a datadog_team_permission_setting resource'
  desc 'Verify that the datadog_team_permission_setting resource exists and has expected properties'

  describe datadog_team_permission_setting(name: attribute('id')) do
    it { should exist }
    its('action') { should_not be_nil }
    its('team_id') { should_not be_nil }
    its('value') { should_not be_nil }
  end
end
