# Code generated by pangea-forge.
# InSpec profile for verifying datadog_role infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_role/ -t datadog://

control 'datadog_role-exists' do
  impact 1.0
  title 'Manages a datadog_role resource'
  desc 'Verify that the datadog_role resource exists and has expected properties'

  describe datadog_role(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
