# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_integration_azure/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogIntegrationAzure
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_integration_azure,
      attributes_class: Datadog::Types::IntegrationAzureAttributes,
      outputs: { id: :id },
      map: [:client_id, :client_secret, :tenant_name],
      map_present: [:app_service_plan_filters, :container_app_filters, :host_filters, :resource_provider_configs],
      map_bool: [:automute, :cspm_enabled, :custom_metrics_enabled, :metrics_enabled, :metrics_enabled_default, :resource_collection_enabled, :usage_metrics_enabled]
  end
  module Datadog
    include DatadogIntegrationAzure
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
