# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_appsec_waf_exclusion_filter/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogAppsecWafExclusionFilter
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_appsec_waf_exclusion_filter,
      attributes_class: Datadog::Types::AppsecWafExclusionFilterAttributes,
      outputs: { id: :id },
      map: [:description],
      map_present: [:event_query, :ip_list, :on_match, :parameters, :path_glob, :rules_target, :scope],
      map_bool: [:enabled]
  end
  module Datadog
    include DatadogAppsecWafExclusionFilter
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
