# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_webhook/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogWebhook
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_webhook,
      attributes_class: Datadog::Types::WebhookAttributes,
      outputs: { id: :id },
      map: [:name, :url],
      map_present: [:custom_headers, :encode_as, :payload]
  end
  module Datadog
    include DatadogWebhook
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
