# Code generated by pangea-forge.
# InSpec profile for verifying datadog_integration_aws_account infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_integration_aws_account/ -t datadog://

control 'datadog_integration_aws_account-exists' do
  impact 1.0
  title 'Manages a datadog_integration_aws_account resource'
  desc 'Verify that the datadog_integration_aws_account resource exists and has expected properties'

  describe datadog_integration_aws_account(name: attribute('id')) do
    it { should exist }
    its('aws_account_id') { should_not be_nil }
    its('aws_partition') { should_not be_nil }
  end
end
