# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class SensitiveDataScannerGroupAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :filter, T::Hash
    attribute :is_enabled, T::Bool
    attribute :name, T::String
    attribute :product_list, T::Array.of(T::String)
    attribute? :description, T::String.optional
    attribute? :samplings, T::Array.of(T::Hash).optional
  end
end
