# frozen_string_literal: true

require 'json'
require 'fileutils'
require_relative 'normalize'
require_relative 'classify'
require_relative 'rules'
require_relative 'engines/timeseries_grid'

module Pangea
  module Datadog
    module Absorb
      # Rung 2 of the staircase: typed Pangea Ruby that reproduces the captured
      # estate exactly. Rung 3 replaces a repeating family with a call into an
      # archetype engine, and verify proves the replacement changed nothing.
      #
      # The emitted shape is chosen per kind, from what actually round-trips to
      # an empty terraform plan against the live estate:
      #
      #   monitors    typed datadog_monitor, plus a lifecycle block ignoring
      #               new_host_delay (deprecated, defaulted to 300 by the
      #               provider, omitted by the API on most monitors)
      #   dashboards  datadog_dashboard_json. The TYPED datadog_dashboard cannot
      #               be used: its `widget` is Array(Hash) at the Ruby type layer
      #               and accepts the API shape, but the provider's widget schema
      #               is a per-type block structure and terraform rejects
      #               {definition, layout} outright.
      #
      # So monitors stay fully refactorable and dashboards land as opaque JSON.
      # Making dashboards refactorable is a different problem -- the
      # pangea-dashboards typed AST -- not a Pangea archetype over attributes.
      #
      # Nothing in this file knows anything about a particular organisation.
      # Which monitors are ours to declare, which dashboards are worth keeping,
      # how monitors group, and which archetypes exist all arrive via Rules.
      class Emit
        HEADER = <<~RUBY
          # frozen_string_literal: true
          #
          # Generated by pangea-datadog-absorb from a live Datadog capture.
          # Regenerate rather than hand-edit: `pangea-datadog-absorb emit`.
          # Every change is gated by `pangea-datadog-absorb verify`, which
          # re-runs this file and diffs it against the capture.
        RUBY

        ENGINES = { Engines::TimeseriesGrid::NAME => Engines::TimeseriesGrid }.freeze

        # See the comment at the assignment site in emit_monitors.
        MONITOR_UNROUNDTRIPPABLE = %i[
          new_host_delay enable_logs_sample groupby_simple_monitor
          require_full_window no_data_timeframe
        ].freeze

        attr_reader :capture, :out_dir, :rules

        def initialize(capture:, out_dir:, rules: Rules.none)
          @capture = capture
          @out_dir = out_dir
          @rules   = rules
        end

        # Returns the import map: terraform address => datadog id.
        # Adoption depends on it -- without an import the first apply would
        # create a duplicate of every live object.
        def run
          FileUtils.mkdir_p(out_dir)
          imports = {}
          imports.merge!(emit_monitors)
          imports.merge!(emit_dashboards)
          imports.merge!(emit_simple(:slos, :datadog_service_level_objective, 'slos') { |p| Normalize.slo(p) })
          imports.merge!(emit_simple(:downtimes, :datadog_downtime, 'downtimes') { |p| Normalize.downtime(p) })
          imports.merge!(emit_logs_pipelines)
          imports.merge!(emit_simple(:logs_metrics, :datadog_logs_metric, 'logs_metrics') do |p|
            Normalize.logs_metric(p)
          end)
          imports.merge!(emit_simple(:logs_indexes, :datadog_logs_index, 'logs_indexes') do |p|
            Normalize.logs_index(p)
          end)
          imports.merge!(emit_simple(:teams, :datadog_team, 'teams') { |p| Normalize.team(p) })
          imports.merge!(emit_roles)
          imports.merge!(emit_simple(:rum_applications, :datadog_rum_application, 'rum_applications') do |p|
            Normalize.rum_application(p)
          end)
          imports.merge!(emit_simple(:apm_retention_filters, :datadog_apm_retention_filter,
                                     'apm_retention_filters',
                                     only: ->(p) { Normalize.apm_retention_filter_adoptable?(p) }) do |p|
            Normalize.apm_retention_filter(p)
          end)
          imports.merge!(emit_simple(:dashboard_lists, :datadog_dashboard_list, 'dashboard_lists') do |p|
            Normalize.dashboard_list(p)
          end)
          imports.merge!(emit_powerpacks)
          File.write(File.join(out_dir, 'imports.json'), "#{JSON.pretty_generate(imports)}\n")
          imports
        end

        def emit_monitors
          imports = {}
          groups  = Hash.new { |h, k| h[k] = [] }

          capture.each(:monitors) do |id, payload|
            next unless rules.adopt?(payload)

            attrs = Normalize.monitor(payload)
            if rules.repair_on_emit? && Classify.tags_corrupted?(payload)
              attrs[:tags] = rules.repair_tags(payload['tags']).sort
            end

            # Provider-schema DEFAULTS whose read does not round-trip. Each has
            # a documented default, and the provider's Read either omits the
            # field (so config setting it diffs) or re-asserts the default (so
            # config omitting it diffs). Either way no static config wins, and
            # the only honest option is to stop managing them.
            #
            # Measured across the 236 captured monitors, absent from the API:
            #   enable_logs_sample      210    groupby_simple_monitor  210
            #   no_data_timeframe       211    new_host_delay          142
            #   require_full_window      48
            #
            # This is the SAME asymmetry the dashboards have: the provider's read
            # does not reproduce its own schema. Naming the fields keeps the
            # trade explicit rather than blanket-ignoring the resource.
            attrs[:lifecycle] = { ignore_changes: MONITOR_UNROUNDTRIPPABLE }

            slug = resource_slug(payload['name'], id)
            groups[rules.group_for(payload)] << [slug, attrs]
            imports["datadog_monitor.#{slug}"] = id
          end

          groups.each do |group, entries|
            write_template("monitors_#{group}", entries.sort_by(&:first)) do |slug, attrs|
              render_resource(:datadog_monitor, slug, attrs)
            end
          end

          imports
        end

        # A powerpack has NO emittable body until `reconcile` has recorded the
        # provider's own post-import state -- there is no projection of the API
        # payload that `datadog_powerpack` accepts. Unreconciled ones are
        # skipped rather than emitted half-formed.
        def emit_powerpacks
          imports = {}
          entries = []

          capture.each(:powerpacks) do |id, payload|
            body = Normalize.powerpack(payload, capture.normalized(:powerpacks, id))
            next if body.nil?

            slug = resource_slug(payload.dig('attributes', 'name'), id)
            entries << [slug, body]
            imports["datadog_powerpack.#{slug}"] = id
          end
          return imports if entries.empty?

          write_template('powerpacks', entries.sort_by(&:first)) do |slug, attrs|
            render_resource(:datadog_powerpack, slug, attrs)
          end
          imports
        end

        # Datadog ships Admin / Standard / Read Only into every account and marks
        # them `managed`. Unlike a read-only pipeline there is no second resource
        # to fall back to -- the provider models managed roles not at all -- so
        # they are skipped outright rather than emitted as something they are
        # not. 3 of this estate's 4 roles are managed.
        def emit_roles
          imports = {}
          entries = []

          capture.each(:roles) do |id, payload|
            next if Normalize.role_managed?(payload)

            slug = resource_slug(payload.dig('attributes', 'name'), id)
            entries << [slug, Normalize.role(payload)]
            imports["datadog_role.#{slug}"] = id
          end
          return imports if entries.empty?

          write_template('roles', entries.sort_by(&:first)) do |slug, attrs|
            render_resource(:datadog_role, slug, attrs)
          end
          imports
        end

        # Datadog's own integration pipelines and an account's custom pipelines
        # come back from ONE endpoint but are TWO provider resources -- the
        # read-only ones carry nothing but `is_enabled`. Emitting a read-only
        # pipeline as a custom one would ask terraform to recreate a pipeline
        # Datadog already ships, next to the original.
        def emit_logs_pipelines
          imports = {}
          custom = []
          integration = []

          capture.each(:logs_pipelines) do |id, payload|
            slug = resource_slug(payload['name'], id)
            if Normalize.logs_pipeline_read_only?(payload)
              integration << [slug, Normalize.logs_integration_pipeline(payload)]
              imports["datadog_logs_integration_pipeline.#{slug}"] = id
            else
              custom << [slug, Normalize.logs_custom_pipeline(payload)]
              imports["datadog_logs_custom_pipeline.#{slug}"] = id
            end
          end

          unless custom.empty?
            write_template('logs_pipelines', custom.sort_by(&:first)) do |slug, attrs|
              render_resource(:datadog_logs_custom_pipeline, slug, attrs)
            end
          end
          unless integration.empty?
            write_template('logs_integration_pipelines', integration.sort_by(&:first)) do |slug, attrs|
              render_resource(:datadog_logs_integration_pipeline, slug, attrs)
            end
          end

          imports
        end

        # SLOs and downtimes need none of the monitor/dashboard machinery: no
        # provenance split, no tiering, no archetypes. One file, one resource per
        # captured object, named off the object's own name.
        def emit_simple(kind, resource, file, only: nil)
          imports = {}
          entries = []

          capture.each(kind) do |id, payload|
            next if only && !only.call(payload)

            slug = resource_slug(payload['name'] || payload.dig('attributes', 'name') ||
                                 payload['message'] || kind.to_s, id)
            entries << [slug, yield(payload)]
            imports["#{resource}.#{slug}"] = id
          end
          return imports if entries.empty?

          write_template(file, entries.sort_by(&:first)) do |slug, attrs|
            render_resource(resource, slug, attrs)
          end
          imports
        end

        def emit_dashboards
          imports = {}
          twins   = rules.dedupe_identical? ? Classify.twin_index(capture) : {}
          entries = []

          capture.each(:dashboards) do |id, payload|
            tier = Classify.dashboard_tier(payload, id: id, rules: rules, twins: twins)
            next if tier == Classify::TIER_RETIRE

            entries << [resource_slug(payload['title'], id), payload, tier, id]
            imports["datadog_dashboard_json.#{resource_slug(payload['title'], id)}"] = id
          end

          # One file per dashboard. A single file holding all of them reached
          # 2.8 MB, which no reviewer can read and no diff can usefully show.
          entries.each do |slug, payload, tier, id|
            if tier == Classify::TIER_ARCHETYPE
              write_archetype(slug, payload)
            else
              body = Normalize.dashboard_json_for(payload, capture.normalized(:dashboards, id))
              write_template(File.join('dashboards', slug), [[slug, body]]) do |name, a|
                render_resource(:datadog_dashboard_json, name, a)
              end
            end
          end

          imports
        end

        # Rung 3. The emitted file calls the engine with the archetype's config
        # table plus the parameters measured off this instance, so the estate's
        # duplication collapses without its content changing.
        def write_archetype(slug, payload)
          arch    = rules.archetype_for(payload['title'])
          derived = derive_archetype_params(arch, payload)

          write_template(File.join('dashboards_archetype', slug), [[slug, derived]],
                         requires: [engine_require(arch.engine)]) do |name, params|
            <<~RUBY
              Pangea::Datadog::Absorb::Engines::#{engine_const(arch.engine)}.build(
                synth,
                name: :#{name},
                #{params.map { |k, v| "#{k}: #{literal(v, 1)}" }.join(",\n    ")}
              )
            RUBY
          end
        end

        # Measured off the live object, never assumed. Which widget carries an
        # empty `time` key and which widget's scope was typed differently are
        # both properties of the instance, not of the archetype.
        def derive_archetype_params(arch, payload)
          widgets = Array(payload['widgets'])
          scopes  = widgets.map { |w| scope_of(w) }
          base    = dominant(scopes)
          over    = scopes.each_with_index.reject { |s, _| s == base }.map { |s, i| [i, s] }.to_h
          time_on = widgets.each_index.select { |i| widgets[i]['definition'].is_a?(Hash) && widgets[i]['definition'].key?('time') }

          {
            title: payload['title'],
            scope: base,
            widgets: arch.widgets,
            group_by: arch.group_by,
            time_on: time_on,
            scope_overrides: over,
            widget_ids: widgets.map { |w| w['id'] },
            layout_type: payload['layout_type'],
            reflow_type: payload['reflow_type'],
            notify_list: payload['notify_list'] || [],
            description: payload['description'].to_s,
            template_variables: payload['template_variables'] || []
          }
        end

        def scope_of(widget)
          query = widget.dig('definition', 'requests', 0, 'queries', 0, 'query').to_s
          query[/\{(.*?)\}/, 1].to_s
        end

        def dominant(values)
          counts = Hash.new(0)
          values.each { |v| counts[v] += 1 }
          counts.max_by { |_, n| n }&.first.to_s
        end

        # Generated code that calls the engine must REQUIRE the engine. Without
        # it the file only runs inside a process that already loaded absorb --
        # the CLI does, a Pangea workspace does not, and neither does the
        # operator's in-cluster compiler. It emitted fine and failed where it
        # was actually deployed.
        def engine_require(engine)
          "pangea/datadog/absorb/engines/#{engine}"
        end

        def engine_const(engine)
          ENGINES.fetch(engine) { raise "unknown archetype engine #{engine.inspect}" }
                 .name.split('::').last
        end

        # ---- rendering ---------------------------------------------------

        # Two group names that camelize to one module would have the second file
        # reopen the first and replace its build method, silently dropping every
        # resource in one of them. That happened once, so it is now an error.
        def write_template(name, entries, requires: [])
          module_name = camelize(File.basename(name))
          @modules ||= {}
          if (taken = @modules[module_name]) && taken != name
            raise "module #{module_name} claimed by both #{taken} and #{name}"
          end

          @modules[module_name] = name
          body = entries.map { |slug, attrs| yield(slug, attrs) }.join("\n")
          path = File.join(out_dir, "#{name}.rb")
          FileUtils.mkdir_p(File.dirname(path))
          File.write(path, <<~RUBY)
            #{HEADER}
            #{requires.map { |r| "require '#{r}'" }.join("\n")}#{"\n" unless requires.empty?}
            module Pangea
              module Absorbed
                module #{module_name}
                  def self.build(synth)
                    synth.extend(Pangea::Resources::Datadog) unless synth.respond_to?(:datadog_monitor)

            #{indent(body, 8)}
                    nil
                  end
                end
              end
            end
          RUBY
        end

        def render_resource(kind, slug, attrs)
          "synth.#{kind}(:#{slug}, #{literal(attrs, 0)})\n"
        end

        # Ruby literals rather than a JSON blob: the emitted file has to be
        # readable and diffable by a human reviewing a production change.
        def literal(value, depth)
          pad  = '  ' * (depth + 1)
          tail = '  ' * depth

          case value
          when Hash
            return '{}' if value.empty?

            body = value.map do |k, v|
              key = k.is_a?(Symbol) ? "#{k}:" : "#{scalar(k)} =>"
              "#{pad}#{key} #{literal(v, depth + 1)}"
            end.join(",\n")
            "{\n#{body}\n#{tail}}"
          when Array
            return '[]' if value.empty?

            body = value.map { |v| "#{pad}#{literal(v, depth + 1)}" }.join(",\n")
            "[\n#{body}\n#{tail}]"
          else
            scalar(value)
          end
        end

        def scalar(value)
          case value
          when String then value.dump
          when Symbol then ":#{value}"
          when nil then 'nil'
          else value.inspect
          end
        end

        def indent(text, spaces)
          pad = ' ' * spaces
          text.lines.map { |l| l.strip.empty? ? l : "#{pad}#{l}" }.join
        end

        # ---- naming ------------------------------------------------------

        # Names must be stable across runs and unique across the estate. Datadog
        # titles collide (five boards in one estate are all "Akeyless GW"), so the
        # id is folded in as a suffix rather than trusted alone.
        def resource_slug(title, id)
          base = title.to_s.downcase.gsub(/[^a-z0-9]+/, '_').gsub(/\A_+|_+\z/, '')
          base = 'unnamed' if base.empty?
          "#{base[0, 60]}_#{id.to_s.gsub(/[^A-Za-z0-9]/, '')}"
        end

        def camelize(name)
          name.split(/[_\s]+/).map { |p| p[0].to_s.upcase + p[1..].to_s }.join
        end
      end
    end
  end
end
