# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_logs_index/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogLogsIndex
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_logs_index,
      attributes_class: Datadog::Types::LogsIndexAttributes,
      outputs: { id: :id, name: :name },
      map: [:name, :filter],
      map_present: [:daily_limit, :daily_limit_reset, :daily_limit_warning_threshold_percentage, :exclusion_filters, :retention_days],
      map_bool: [:disable_daily_limit]
  end
  module Datadog
    include DatadogLogsIndex
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
