# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class LogsIndexAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :filter, T::Hash
    attribute :name, T::String
    attribute? :daily_limit, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :daily_limit_reset, T::Hash.optional
    attribute? :daily_limit_warning_threshold_percentage, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :disable_daily_limit, T::Bool.optional
    attribute? :exclusion_filter, T::Array.of(T::Hash).optional
    attribute? :flex_retention_days, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :retention_days, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
