# Code generated by pangea-forge.
# InSpec profile for verifying datadog_apm_retention_filter infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_apm_retention_filter/ -t datadog://

control 'datadog_apm_retention_filter-exists' do
  impact 1.0
  title 'Manages a datadog_apm_retention_filter resource'
  desc 'Verify that the datadog_apm_retention_filter resource exists and has expected properties'

  describe datadog_apm_retention_filter(name: attribute('id')) do
    it { should exist }
    its('enabled') { should_not be_nil }
    its('filter_type') { should_not be_nil }
    its('name') { should_not be_nil }
    its('rate') { should_not be_nil }
  end
end
