# Code generated by pangea-forge.
# InSpec profile for verifying datadog_on_call_escalation_policy infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_on_call_escalation_policy/ -t datadog://

control 'datadog_on_call_escalation_policy-exists' do
  impact 1.0
  title 'Manages a datadog_on_call_escalation_policy resource'
  desc 'Verify that the datadog_on_call_escalation_policy resource exists and has expected properties'

  describe datadog_on_call_escalation_policy(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
