# Code generated by pangea-forge.
# InSpec profile for verifying datadog_logs_index infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_logs_index/ -t datadog://

control 'datadog_logs_index-exists' do
  impact 1.0
  title 'Manages a datadog_logs_index resource'
  desc 'Verify that the datadog_logs_index resource exists and has expected properties'

  describe datadog_logs_index(name: attribute('id')) do
    it { should exist }
    its('filter') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
