# Code generated by pangea-forge.
# InSpec profile for verifying datadog_monitor_json infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_monitor_json/ -t datadog://

control 'datadog_monitor_json-exists' do
  impact 1.0
  title 'Manages a datadog_monitor_json resource'
  desc 'Verify that the datadog_monitor_json resource exists and has expected properties'

  describe datadog_monitor_json(name: attribute('id')) do
    it { should exist }
    its('monitor') { should_not be_nil }
  end
end
