# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_logs_custom_destination/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogLogsCustomDestination
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_logs_custom_destination,
      attributes_class: Datadog::Types::LogsCustomDestinationAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:elasticsearch_destination, :forward_tags_restriction_list, :forward_tags_restriction_list_type, :http_destination, :microsoft_sentinel_destination, :query, :splunk_destination],
      map_bool: [:enabled, :forward_tags]
  end
  module Datadog
    include DatadogLogsCustomDestination
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
