# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class LogsCustomDestinationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :name, T::String
    attribute? :elasticsearch_destination, T::Array.of(T::Hash).optional
    attribute? :enabled, T::Bool.optional
    attribute? :forward_tags, T::Bool.optional
    attribute? :forward_tags_restriction_list, T::Array.of(T::String).optional
    attribute? :forward_tags_restriction_list_type, T::String.optional
    attribute? :http_destination, T::Array.of(T::Hash).optional
    attribute? :microsoft_sentinel_destination, T::Array.of(T::Hash).optional
    attribute? :query, T::String.optional
    attribute? :splunk_destination, T::Array.of(T::Hash).optional
  end
end
