# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class LogsCustomPipelineAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :filter, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :is_enabled, T::Bool.optional
    attribute? :processor, T::Array.of(T::Hash).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
