# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_integration_slack_channel/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogIntegrationSlackChannel
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_integration_slack_channel,
      attributes_class: Datadog::Types::IntegrationSlackChannelAttributes,
      outputs: { id: :id },
      map: [:account_name, :channel_name, :display]
  end
  module Datadog
    include DatadogIntegrationSlackChannel
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
