# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_integration_confluent_account/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogIntegrationConfluentAccount
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_integration_confluent_account,
      attributes_class: Datadog::Types::IntegrationConfluentAccountAttributes,
      outputs: { id: :id },
      map: [:api_key, :api_secret],
      map_present: [:tags]
  end
  module Datadog
    include DatadogIntegrationConfluentAccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
