# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class IntegrationConfluentAccountAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :api_key, T::String
    attribute :api_secret, T::String
    attribute? :tags, T::Array.of(T::String).optional
  end
end
