# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_rum_retention_filter/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogRumRetentionFilter
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_rum_retention_filter,
      attributes_class: Datadog::Types::RumRetentionFilterAttributes,
      outputs: { id: :id },
      map: [:application_id, :event_type, :name, :sample_rate],
      map_present: [:query],
      map_bool: [:enabled]
  end
  module Datadog
    include DatadogRumRetentionFilter
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
