# Code generated by pangea-forge.
# InSpec profile for verifying datadog_authn_mapping infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_authn_mapping/ -t datadog://

control 'datadog_authn_mapping-exists' do
  impact 1.0
  title 'Manages a datadog_authn_mapping resource'
  desc 'Verify that the datadog_authn_mapping resource exists and has expected properties'

  describe datadog_authn_mapping(name: attribute('id')) do
    it { should exist }
    its('key') { should_not be_nil }
    its('value') { should_not be_nil }
  end
end
