# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class DashboardJsonAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :dashboard, T::String
    attribute? :dashboard_lists, T::Array.of((T::Coercible::Integer | T::Coercible::Float)).optional
    attribute? :url, T::String.optional
  end
end
