# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_downtime_schedule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogDowntimeSchedule
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_downtime_schedule,
      attributes_class: Datadog::Types::DowntimeScheduleAttributes,
      outputs: { id: :id },
      map: [:scope],
      map_present: [:display_timezone, :message, :monitor_identifier, :notify_end_states, :notify_end_types, :one_time_schedule, :recurring_schedule],
      map_bool: [:mute_first_recovery_notification]
  end
  module Datadog
    include DatadogDowntimeSchedule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
