# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_logs_pipeline_order/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogLogsPipelineOrder
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_logs_pipeline_order,
      attributes_class: Datadog::Types::LogsPipelineOrderAttributes,
      outputs: { id: :id },
      map: [:name, :pipelines]
  end
  module Datadog
    include DatadogLogsPipelineOrder
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
