# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_app_builder_app/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogAppBuilderApp
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_app_builder_app,
      attributes_class: Datadog::Types::AppBuilderAppAttributes,
      outputs: { id: :id },
      map: [:app_json],
      map_present: [:action_query_names_to_connection_ids, :description, :name, :root_instance_name],
      map_bool: [:published]
  end
  module Datadog
    include DatadogAppBuilderApp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
