# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class AppBuilderAppAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :app_json, T::String
    attribute? :action_query_names_to_connection_ids, T::Hash.optional
    attribute? :description, T::String.optional
    attribute? :name, T::String.optional
    attribute? :published, T::Bool.optional
    attribute? :root_instance_name, T::String.optional
  end
end
