# Code generated by pangea-forge.
# InSpec profile for verifying datadog_service_account infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set DATADOG_TOKEN and DATADOG_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/datadog_service_account/ -t datadog://

control 'datadog_service_account-exists' do
  impact 1.0
  title 'Manages a datadog_service_account resource'
  desc 'Verify that the datadog_service_account resource exists and has expected properties'

  describe datadog_service_account(name: attribute('id')) do
    it { should exist }
    its('email') { should_not be_nil }
  end
end
