# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_synthetics_test/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogSyntheticsTest
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_synthetics_test,
      attributes_class: Datadog::Types::SyntheticsTestAttributes,
      outputs: { id: :id },
      map: [:locations, :name, :status, :type],
      map_present: [:api_step, :assertion, :browser_step, :browser_variable, :config_initial_application_arguments, :config_variable, :device_ids, :message, :mobile_options_list, :mobile_step, :options_list, :request_basicauth, :request_client_certificate, :request_definition, :request_file, :request_headers, :request_metadata, :request_proxy, :request_query, :set_cookie, :subtype, :tags, :variables_from_script],
      map_bool: [:force_delete_dependencies]
  end
  module Datadog
    include DatadogSyntheticsTest
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
