# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/datadog_types'

module Pangea::Resources::Datadog::Types
  class SyntheticsTestAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Datadog::Types

    attribute? :config, T::String.optional
    attribute :locations, T::Array.of(T::String)
    attribute? :message, T::String.optional
    attribute :name, T::String
    attribute? :options, T::String.optional
    attribute :status, T::String
    attribute? :subtype, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute :type, T::String
  end
end
