# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_integration_aws_external_id/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogIntegrationAwsExternalId
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_integration_aws_external_id,
      attributes_class: Datadog::Types::IntegrationAwsExternalIdAttributes,
      outputs: { id: :id }
  end
  module Datadog
    include DatadogIntegrationAwsExternalId
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
