# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_integration_aws_event_bridge/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogIntegrationAwsEventBridge
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_integration_aws_event_bridge,
      attributes_class: Datadog::Types::IntegrationAwsEventBridgeAttributes,
      outputs: { id: :id },
      map: [:account_id, :event_generator_name, :region],
      map_bool: [:create_event_bus]
  end
  module Datadog
    include DatadogIntegrationAwsEventBridge
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
