# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Datadog::Types
  include Dry.Types()

  class MetricTagConfigurationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Datadog::Types

    attribute :metric_name, T::String
    attribute :metric_type, T::String
    attribute :tags, T::Array.of(T::String)
    attribute? :aggregations, T::Array.of(T::Hash).optional
    attribute? :exclude_tags_mode, T::Bool.optional
    attribute? :include_percentiles, T::Bool.optional
  end
end
