# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/datadog_gcp_uc_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module DatadogGcpUcConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :datadog_gcp_uc_config,
      attributes_class: Datadog::Types::GcpUcConfigAttributes,
      outputs: { id: :id },
      map: [:billing_account_id, :bucket_name, :export_dataset_name, :export_project_name, :service_account],
      map_present: [:export_prefix]
  end
  module Datadog
    include DatadogGcpUcConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Datadog)
