# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_dashboard resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogDashboard do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { layout_type: 'test-value', title: 'test-value' } }

  describe ':datadog_dashboard' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_dashboard', 'test')
        validate_required_attributes(config, [:layout_type, :title])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_dashboard('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_dashboard)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_dashboard('test', required_attrs)

        expect(ref.id).to eq("${datadog_dashboard.test.id}")
        expect(ref.dashboard_lists_removed).to eq("${datadog_dashboard.test.dashboard_lists_removed}")
        expect(ref.url).to eq("${datadog_dashboard.test.url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_dashboard', 'test')
        expect(config).not_to have_key('dashboard_lists_removed')
        expect(config).not_to have_key('url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ dashboard_lists: [3.14], description: 'test-value', is_read_only: true, notify_list: ['test-value'], reflow_type: 'test-value', restricted_roles: ['test-value'], tab: [{ 'key1' => 'val1' }], tags: ['test-value'], template_variable: [{ 'key1' => 'val1' }], template_variable_preset: [{ 'key1' => 'val1' }], url: 'test-value', widget: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_dashboard', 'full')
        expect(config).to have_key('dashboard_lists')
        expect(config).to have_key('description')
        expect(config).to have_key('is_read_only')
        expect(config).to have_key('notify_list')
        expect(config).to have_key('reflow_type')
        expect(config).to have_key('restricted_roles')
        expect(config).to have_key('tab')
        expect(config).to have_key('tags')
        expect(config).to have_key('template_variable')
        expect(config).to have_key('template_variable_preset')
        expect(config).to have_key('url')
        expect(config).to have_key('widget')
      end
    end

    context 'optional attributes' do
      it 'includes dashboard_lists when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(dashboard_lists: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('dashboard_lists')
      end

      it 'omits dashboard_lists when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('dashboard_lists')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes is_read_only when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(is_read_only: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('is_read_only')
      end

      it 'omits is_read_only when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('is_read_only')
      end
      it 'includes notify_list when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(notify_list: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('notify_list')
      end

      it 'omits notify_list when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('notify_list')
      end
      it 'includes reflow_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(reflow_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('reflow_type')
      end

      it 'omits reflow_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('reflow_type')
      end
      it 'includes restricted_roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(restricted_roles: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('restricted_roles')
      end

      it 'omits restricted_roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('restricted_roles')
      end
      it 'includes tab when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(tab: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('tab')
      end

      it 'omits tab when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('tab')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes template_variable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(template_variable: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('template_variable')
      end

      it 'omits template_variable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('template_variable')
      end
      it 'includes template_variable_preset when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(template_variable_preset: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('template_variable_preset')
      end

      it 'omits template_variable_preset when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('template_variable_preset')
      end
      it 'includes url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('url')
      end

      it 'omits url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('url')
      end
      it 'includes widget when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('opt', required_attrs.merge(widget: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'opt')
        expect(config).to have_key('widget')
      end

      it 'omits widget when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_dashboard', 'minimal')
        expect(config).not_to have_key('widget')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts is_read_only=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_read_only: val)
          synth.datadog_dashboard("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_dashboard', "bool_#{val}")
          expect(config['is_read_only']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_dashboard', 'typed')
        expect(config['layout_type']).to be_a(String)
        expect(config['title']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_dashboard('first', required_attrs)
        synth.datadog_dashboard('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_dashboard')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_dashboard,
    method: :datadog_dashboard,
    required_attrs: { layout_type: 'test-value', title: 'test-value' },
    expected_outputs: [:id, :dashboard_lists_removed, :url],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:is_read_only]
end
