# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_api_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogApiKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':datadog_api_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_api_key', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_api_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_api_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_api_key('test', required_attrs)

        expect(ref.id).to eq("${datadog_api_key.test.id}")
        expect(ref.key).to eq("${datadog_api_key.test.key}")
        expect(ref.remote_config_read_enabled).to eq("${datadog_api_key.test.remote_config_read_enabled}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_api_key', 'test')
        expect(config).not_to have_key('key')
        expect(config).not_to have_key('remote_config_read_enabled')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ remote_config_read_enabled: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_api_key('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_api_key', 'full')
        expect(config).to have_key('remote_config_read_enabled')
      end
    end

    context 'optional attributes' do
      it 'includes remote_config_read_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_api_key('opt', required_attrs.merge(remote_config_read_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_api_key', 'opt')
        expect(config).to have_key('remote_config_read_enabled')
      end

      it 'omits remote_config_read_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_api_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_api_key', 'minimal')
        expect(config).not_to have_key('remote_config_read_enabled')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:key]
        expect(sensitive_fields).to include(:key)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts remote_config_read_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(remote_config_read_enabled: val)
          synth.datadog_api_key("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_api_key', "bool_#{val}")
          expect(config['remote_config_read_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_api_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_api_key', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_api_key('first', required_attrs)
        synth.datadog_api_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_api_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_api_key,
    method: :datadog_api_key,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :key, :remote_config_read_enabled],
    sensitive_fields: [:key],
    immutable_fields: [],
    boolean_fields: [:remote_config_read_enabled]
end
