# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_rum_metric resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogRumMetric do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { event_type: 'test-value', name: 'test-value' } }

  describe ':datadog_rum_metric' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_rum_metric', 'test')
        validate_required_attributes(config, [:event_type, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_rum_metric('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_rum_metric)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_rum_metric('test', required_attrs)

        expect(ref.id).to eq("${datadog_rum_metric.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ compute: { 'key1' => 'val1' }, filter: { 'key1' => 'val1' }, group_by: [{ 'key1' => 'val1' }], uniqueness: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_rum_metric', 'full')
        expect(config).to have_key('compute')
        expect(config).to have_key('filter')
        expect(config).to have_key('group_by')
        expect(config).to have_key('uniqueness')
      end
    end

    context 'optional attributes' do
      it 'includes compute when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('opt', required_attrs.merge(compute: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_rum_metric', 'opt')
        expect(config).to have_key('compute')
      end

      it 'omits compute when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_rum_metric', 'minimal')
        expect(config).not_to have_key('compute')
      end
      it 'includes filter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('opt', required_attrs.merge(filter: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_rum_metric', 'opt')
        expect(config).to have_key('filter')
      end

      it 'omits filter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_rum_metric', 'minimal')
        expect(config).not_to have_key('filter')
      end
      it 'includes group_by when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('opt', required_attrs.merge(group_by: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_rum_metric', 'opt')
        expect(config).to have_key('group_by')
      end

      it 'omits group_by when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_rum_metric', 'minimal')
        expect(config).not_to have_key('group_by')
      end
      it 'includes uniqueness when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('opt', required_attrs.merge(uniqueness: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_rum_metric', 'opt')
        expect(config).to have_key('uniqueness')
      end

      it 'omits uniqueness when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_rum_metric', 'minimal')
        expect(config).not_to have_key('uniqueness')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_rum_metric', 'typed')
        expect(config['event_type']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_rum_metric('first', required_attrs)
        synth.datadog_rum_metric('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_rum_metric')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_rum_metric,
    method: :datadog_rum_metric,
    required_attrs: { event_type: 'test-value', name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
