# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_logs_index resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogLogsIndex do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { filter: { 'key1' => 'val1' }, name: 'test-value' } }

  describe ':datadog_logs_index' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_logs_index', 'test')
        validate_required_attributes(config, [:filter, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_logs_index('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_logs_index)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_logs_index('test', required_attrs)

        expect(ref.id).to eq("${datadog_logs_index.test.id}")
        expect(ref.daily_limit_warning_threshold_percentage).to eq("${datadog_logs_index.test.daily_limit_warning_threshold_percentage}")
        expect(ref.disable_daily_limit).to eq("${datadog_logs_index.test.disable_daily_limit}")
        expect(ref.flex_retention_days).to eq("${datadog_logs_index.test.flex_retention_days}")
        expect(ref.retention_days).to eq("${datadog_logs_index.test.retention_days}")
        expect(ref.tags).to eq("${datadog_logs_index.test.tags}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_logs_index', 'test')
        expect(config).not_to have_key('daily_limit_warning_threshold_percentage')
        expect(config).not_to have_key('disable_daily_limit')
        expect(config).not_to have_key('flex_retention_days')
        expect(config).not_to have_key('retention_days')
        expect(config).not_to have_key('tags')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ daily_limit: 3.14, daily_limit_reset: { 'key1' => 'val1' }, daily_limit_warning_threshold_percentage: 3.14, disable_daily_limit: true, exclusion_filter: [{ 'key1' => 'val1' }], flex_retention_days: 3.14, retention_days: 3.14, tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_logs_index', 'full')
        expect(config).to have_key('daily_limit')
        expect(config).to have_key('daily_limit_reset')
        expect(config).to have_key('daily_limit_warning_threshold_percentage')
        expect(config).to have_key('disable_daily_limit')
        expect(config).to have_key('exclusion_filter')
        expect(config).to have_key('flex_retention_days')
        expect(config).to have_key('retention_days')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes daily_limit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('opt', required_attrs.merge(daily_limit: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'opt')
        expect(config).to have_key('daily_limit')
      end

      it 'omits daily_limit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'minimal')
        expect(config).not_to have_key('daily_limit')
      end
      it 'includes daily_limit_reset when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('opt', required_attrs.merge(daily_limit_reset: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'opt')
        expect(config).to have_key('daily_limit_reset')
      end

      it 'omits daily_limit_reset when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'minimal')
        expect(config).not_to have_key('daily_limit_reset')
      end
      it 'includes daily_limit_warning_threshold_percentage when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('opt', required_attrs.merge(daily_limit_warning_threshold_percentage: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'opt')
        expect(config).to have_key('daily_limit_warning_threshold_percentage')
      end

      it 'omits daily_limit_warning_threshold_percentage when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'minimal')
        expect(config).not_to have_key('daily_limit_warning_threshold_percentage')
      end
      it 'includes disable_daily_limit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('opt', required_attrs.merge(disable_daily_limit: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'opt')
        expect(config).to have_key('disable_daily_limit')
      end

      it 'omits disable_daily_limit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'minimal')
        expect(config).not_to have_key('disable_daily_limit')
      end
      it 'includes exclusion_filter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('opt', required_attrs.merge(exclusion_filter: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'opt')
        expect(config).to have_key('exclusion_filter')
      end

      it 'omits exclusion_filter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'minimal')
        expect(config).not_to have_key('exclusion_filter')
      end
      it 'includes flex_retention_days when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('opt', required_attrs.merge(flex_retention_days: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'opt')
        expect(config).to have_key('flex_retention_days')
      end

      it 'omits flex_retention_days when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'minimal')
        expect(config).not_to have_key('flex_retention_days')
      end
      it 'includes retention_days when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('opt', required_attrs.merge(retention_days: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'opt')
        expect(config).to have_key('retention_days')
      end

      it 'omits retention_days when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'minimal')
        expect(config).not_to have_key('retention_days')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_logs_index', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_daily_limit=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_daily_limit: val)
          synth.datadog_logs_index("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_logs_index', "bool_#{val}")
          expect(config['disable_daily_limit']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_logs_index', 'typed')
        expect(config['filter']).to be_a(Hash)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_logs_index('first', required_attrs)
        synth.datadog_logs_index('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_logs_index')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_logs_index,
    method: :datadog_logs_index,
    required_attrs: { filter: { 'key1' => 'val1' }, name: 'test-value' },
    expected_outputs: [:id, :daily_limit_warning_threshold_percentage, :disable_daily_limit, :flex_retention_days, :retention_days, :tags],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disable_daily_limit]
end
