# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_child_organization resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogChildOrganization do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':datadog_child_organization' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_child_organization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_child_organization', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_child_organization('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_child_organization)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_child_organization('test', required_attrs)

        expect(ref.id).to eq("${datadog_child_organization.test.id}")
        expect(ref.api_key).to eq("${datadog_child_organization.test.api_key}")
        expect(ref.application_key).to eq("${datadog_child_organization.test.application_key}")
        expect(ref.description).to eq("${datadog_child_organization.test.description}")
        expect(ref.public_id).to eq("${datadog_child_organization.test.public_id}")
        expect(ref.settings).to eq("${datadog_child_organization.test.settings}")
        expect(ref.user).to eq("${datadog_child_organization.test.user}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_child_organization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_child_organization', 'test')
        expect(config).not_to have_key('api_key')
        expect(config).not_to have_key('application_key')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('public_id')
        expect(config).not_to have_key('settings')
        expect(config).not_to have_key('user')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_child_organization('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_child_organization', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_child_organization('first', required_attrs)
        synth.datadog_child_organization('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_child_organization')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_child_organization,
    method: :datadog_child_organization,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :api_key, :application_key, :description, :public_id, :settings, :user],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
