# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_aws_cur_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogAwsCurConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', bucket_name: 'test-value', report_name: 'test-value', report_prefix: 'test-value' } }

  describe ':datadog_aws_cur_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_aws_cur_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_aws_cur_config', 'test')
        validate_required_attributes(config, [:account_id, :bucket_name, :report_name, :report_prefix])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_aws_cur_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_aws_cur_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_aws_cur_config('test', required_attrs)

        expect(ref.id).to eq("${datadog_aws_cur_config.test.id}")
        expect(ref.created_at).to eq("${datadog_aws_cur_config.test.created_at}")
        expect(ref.error_messages).to eq("${datadog_aws_cur_config.test.error_messages}")
        expect(ref.status).to eq("${datadog_aws_cur_config.test.status}")
        expect(ref.status_updated_at).to eq("${datadog_aws_cur_config.test.status_updated_at}")
        expect(ref.updated_at).to eq("${datadog_aws_cur_config.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_aws_cur_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_aws_cur_config', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('error_messages')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('status_updated_at')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ account_filters: { 'key1' => 'val1' }, bucket_region: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_aws_cur_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_aws_cur_config', 'full')
        expect(config).to have_key('account_filters')
        expect(config).to have_key('bucket_region')
      end
    end

    context 'optional attributes' do
      it 'includes account_filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_aws_cur_config('opt', required_attrs.merge(account_filters: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_aws_cur_config', 'opt')
        expect(config).to have_key('account_filters')
      end

      it 'omits account_filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_aws_cur_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_aws_cur_config', 'minimal')
        expect(config).not_to have_key('account_filters')
      end
      it 'includes bucket_region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_aws_cur_config('opt', required_attrs.merge(bucket_region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_aws_cur_config', 'opt')
        expect(config).to have_key('bucket_region')
      end

      it 'omits bucket_region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_aws_cur_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_aws_cur_config', 'minimal')
        expect(config).not_to have_key('bucket_region')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_aws_cur_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_aws_cur_config', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['bucket_name']).to be_a(String)
        expect(config['report_name']).to be_a(String)
        expect(config['report_prefix']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_aws_cur_config('first', required_attrs)
        synth.datadog_aws_cur_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_aws_cur_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_aws_cur_config,
    method: :datadog_aws_cur_config,
    required_attrs: { account_id: 'test-value', bucket_name: 'test-value', report_name: 'test-value', report_prefix: 'test-value' },
    expected_outputs: [:id, :created_at, :error_messages, :status, :status_updated_at, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
