# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_user resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogUser do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { email: 'test-value' } }

  describe ':datadog_user' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_user', 'test')
        validate_required_attributes(config, [:email])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_user('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_user)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_user('test', required_attrs)

        expect(ref.id).to eq("${datadog_user.test.id}")
        expect(ref.name).to eq("${datadog_user.test.name}")
        expect(ref.roles).to eq("${datadog_user.test.roles}")
        expect(ref.user_invitation_id).to eq("${datadog_user.test.user_invitation_id}")
        expect(ref.verified).to eq("${datadog_user.test.verified}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_user', 'test')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('roles')
        expect(config).not_to have_key('user_invitation_id')
        expect(config).not_to have_key('verified')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ disabled: true, name: 'test-value', roles: ['test-value'], send_user_invitation: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_user', 'full')
        expect(config).to have_key('disabled')
        expect(config).to have_key('name')
        expect(config).to have_key('roles')
        expect(config).to have_key('send_user_invitation')
      end
    end

    context 'optional attributes' do
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_user', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_user', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_user', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_user', 'minimal')
        expect(config).not_to have_key('name')
      end
      it 'includes roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('opt', required_attrs.merge(roles: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_user', 'opt')
        expect(config).to have_key('roles')
      end

      it 'omits roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_user', 'minimal')
        expect(config).not_to have_key('roles')
      end
      it 'includes send_user_invitation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('opt', required_attrs.merge(send_user_invitation: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_user', 'opt')
        expect(config).to have_key('send_user_invitation')
      end

      it 'omits send_user_invitation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_user', 'minimal')
        expect(config).not_to have_key('send_user_invitation')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.datadog_user("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_user', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts send_user_invitation=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(send_user_invitation: val)
          synth.datadog_user("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_user', "bool_#{val}")
          expect(config['send_user_invitation']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_user', 'typed')
        expect(config['email']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_user('first', required_attrs)
        synth.datadog_user('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_user')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_user,
    method: :datadog_user,
    required_attrs: { email: 'test-value' },
    expected_outputs: [:id, :name, :roles, :user_invitation_id, :verified],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled, :send_user_invitation]
end
