# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_integration_ms_teams_workflows_webhook_handle resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogIntegrationMsTeamsWorkflowsWebhookHandle do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', url: 'test-value' } }

  describe ':datadog_integration_ms_teams_workflows_webhook_handle' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_ms_teams_workflows_webhook_handle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_integration_ms_teams_workflows_webhook_handle', 'test')
        validate_required_attributes(config, [:name, :url])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_ms_teams_workflows_webhook_handle('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_integration_ms_teams_workflows_webhook_handle)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_ms_teams_workflows_webhook_handle('test', required_attrs)

        expect(ref.id).to eq("${datadog_integration_ms_teams_workflows_webhook_handle.test.id}")
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:url]
        expect(sensitive_fields).to include(:url)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_ms_teams_workflows_webhook_handle('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_ms_teams_workflows_webhook_handle', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['url']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_ms_teams_workflows_webhook_handle('first', required_attrs)
        synth.datadog_integration_ms_teams_workflows_webhook_handle('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_integration_ms_teams_workflows_webhook_handle')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_integration_ms_teams_workflows_webhook_handle,
    method: :datadog_integration_ms_teams_workflows_webhook_handle,
    required_attrs: { name: 'test-value', url: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [:url],
    immutable_fields: [],
    boolean_fields: []
end
