# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_integration_gcp resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogIntegrationGcp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { client_email: 'test-value', client_id: 'test-value', private_key: 'test-value', private_key_id: 'test-value', project_id: 'test-value' } }

  describe ':datadog_integration_gcp' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'test')
        validate_required_attributes(config, [:client_email, :client_id, :private_key, :private_key_id, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_gcp('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_integration_gcp)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_gcp('test', required_attrs)

        expect(ref.id).to eq("${datadog_integration_gcp.test.id}")
        expect(ref.automute).to eq("${datadog_integration_gcp.test.automute}")
        expect(ref.cloud_run_revision_filters).to eq("${datadog_integration_gcp.test.cloud_run_revision_filters}")
        expect(ref.cspm_resource_collection_enabled).to eq("${datadog_integration_gcp.test.cspm_resource_collection_enabled}")
        expect(ref.host_filters).to eq("${datadog_integration_gcp.test.host_filters}")
        expect(ref.is_resource_change_collection_enabled).to eq("${datadog_integration_gcp.test.is_resource_change_collection_enabled}")
        expect(ref.is_security_command_center_enabled).to eq("${datadog_integration_gcp.test.is_security_command_center_enabled}")
        expect(ref.monitored_resource_configs).to eq("${datadog_integration_gcp.test.monitored_resource_configs}")
        expect(ref.resource_collection_enabled).to eq("${datadog_integration_gcp.test.resource_collection_enabled}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_gcp', 'test')
        expect(config).not_to have_key('automute')
        expect(config).not_to have_key('cloud_run_revision_filters')
        expect(config).not_to have_key('cspm_resource_collection_enabled')
        expect(config).not_to have_key('host_filters')
        expect(config).not_to have_key('is_resource_change_collection_enabled')
        expect(config).not_to have_key('is_security_command_center_enabled')
        expect(config).not_to have_key('monitored_resource_configs')
        expect(config).not_to have_key('resource_collection_enabled')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ automute: true, cloud_run_revision_filters: ['test-value'], cspm_resource_collection_enabled: true, host_filters: 'test-value', is_resource_change_collection_enabled: true, is_security_command_center_enabled: true, monitored_resource_configs: [{ 'key1' => 'val1' }], resource_collection_enabled: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_gcp', 'full')
        expect(config).to have_key('automute')
        expect(config).to have_key('cloud_run_revision_filters')
        expect(config).to have_key('cspm_resource_collection_enabled')
        expect(config).to have_key('host_filters')
        expect(config).to have_key('is_resource_change_collection_enabled')
        expect(config).to have_key('is_security_command_center_enabled')
        expect(config).to have_key('monitored_resource_configs')
        expect(config).to have_key('resource_collection_enabled')
      end
    end

    context 'optional attributes' do
      it 'includes automute when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('opt', required_attrs.merge(automute: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'opt')
        expect(config).to have_key('automute')
      end

      it 'omits automute when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'minimal')
        expect(config).not_to have_key('automute')
      end
      it 'includes cloud_run_revision_filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('opt', required_attrs.merge(cloud_run_revision_filters: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'opt')
        expect(config).to have_key('cloud_run_revision_filters')
      end

      it 'omits cloud_run_revision_filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'minimal')
        expect(config).not_to have_key('cloud_run_revision_filters')
      end
      it 'includes cspm_resource_collection_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('opt', required_attrs.merge(cspm_resource_collection_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'opt')
        expect(config).to have_key('cspm_resource_collection_enabled')
      end

      it 'omits cspm_resource_collection_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'minimal')
        expect(config).not_to have_key('cspm_resource_collection_enabled')
      end
      it 'includes host_filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('opt', required_attrs.merge(host_filters: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'opt')
        expect(config).to have_key('host_filters')
      end

      it 'omits host_filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'minimal')
        expect(config).not_to have_key('host_filters')
      end
      it 'includes is_resource_change_collection_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('opt', required_attrs.merge(is_resource_change_collection_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'opt')
        expect(config).to have_key('is_resource_change_collection_enabled')
      end

      it 'omits is_resource_change_collection_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'minimal')
        expect(config).not_to have_key('is_resource_change_collection_enabled')
      end
      it 'includes is_security_command_center_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('opt', required_attrs.merge(is_security_command_center_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'opt')
        expect(config).to have_key('is_security_command_center_enabled')
      end

      it 'omits is_security_command_center_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'minimal')
        expect(config).not_to have_key('is_security_command_center_enabled')
      end
      it 'includes monitored_resource_configs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('opt', required_attrs.merge(monitored_resource_configs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'opt')
        expect(config).to have_key('monitored_resource_configs')
      end

      it 'omits monitored_resource_configs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'minimal')
        expect(config).not_to have_key('monitored_resource_configs')
      end
      it 'includes resource_collection_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('opt', required_attrs.merge(resource_collection_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'opt')
        expect(config).to have_key('resource_collection_enabled')
      end

      it 'omits resource_collection_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp', 'minimal')
        expect(config).not_to have_key('resource_collection_enabled')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:private_key]
        expect(sensitive_fields).to include(:private_key)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts automute=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(automute: val)
          synth.datadog_integration_gcp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp', "bool_#{val}")
          expect(config['automute']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts cspm_resource_collection_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(cspm_resource_collection_enabled: val)
          synth.datadog_integration_gcp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp', "bool_#{val}")
          expect(config['cspm_resource_collection_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_resource_change_collection_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_resource_change_collection_enabled: val)
          synth.datadog_integration_gcp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp', "bool_#{val}")
          expect(config['is_resource_change_collection_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_security_command_center_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_security_command_center_enabled: val)
          synth.datadog_integration_gcp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp', "bool_#{val}")
          expect(config['is_security_command_center_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts resource_collection_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(resource_collection_enabled: val)
          synth.datadog_integration_gcp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp', "bool_#{val}")
          expect(config['resource_collection_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_gcp', 'typed')
        expect(config['client_email']).to be_a(String)
        expect(config['client_id']).to be_a(String)
        expect(config['private_key']).to be_a(String)
        expect(config['private_key_id']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp('first', required_attrs)
        synth.datadog_integration_gcp('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_integration_gcp')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_integration_gcp,
    method: :datadog_integration_gcp,
    required_attrs: { client_email: 'test-value', client_id: 'test-value', private_key: 'test-value', private_key_id: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :automute, :cloud_run_revision_filters, :cspm_resource_collection_enabled, :host_filters, :is_resource_change_collection_enabled, :is_security_command_center_enabled, :monitored_resource_configs, :resource_collection_enabled],
    sensitive_fields: [:private_key],
    immutable_fields: [],
    boolean_fields: [:automute, :cspm_resource_collection_enabled, :is_resource_change_collection_enabled, :is_security_command_center_enabled, :resource_collection_enabled]
end
