# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_app_builder_app resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogAppBuilderApp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { app_json: 'test-value' } }

  describe ':datadog_app_builder_app' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'test')
        validate_required_attributes(config, [:app_json])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_app_builder_app('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_app_builder_app)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_app_builder_app('test', required_attrs)

        expect(ref.id).to eq("${datadog_app_builder_app.test.id}")
        expect(ref.action_query_names_to_connection_ids).to eq("${datadog_app_builder_app.test.action_query_names_to_connection_ids}")
        expect(ref.description).to eq("${datadog_app_builder_app.test.description}")
        expect(ref.name).to eq("${datadog_app_builder_app.test.name}")
        expect(ref.published).to eq("${datadog_app_builder_app.test.published}")
        expect(ref.root_instance_name).to eq("${datadog_app_builder_app.test.root_instance_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_app_builder_app', 'test')
        expect(config).not_to have_key('action_query_names_to_connection_ids')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('published')
        expect(config).not_to have_key('root_instance_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ action_query_names_to_connection_ids: { 'key1' => 'val1' }, description: 'test-value', name: 'test-value', published: true, root_instance_name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_app_builder_app', 'full')
        expect(config).to have_key('action_query_names_to_connection_ids')
        expect(config).to have_key('description')
        expect(config).to have_key('name')
        expect(config).to have_key('published')
        expect(config).to have_key('root_instance_name')
      end
    end

    context 'optional attributes' do
      it 'includes action_query_names_to_connection_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('opt', required_attrs.merge(action_query_names_to_connection_ids: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'opt')
        expect(config).to have_key('action_query_names_to_connection_ids')
      end

      it 'omits action_query_names_to_connection_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'minimal')
        expect(config).not_to have_key('action_query_names_to_connection_ids')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'minimal')
        expect(config).not_to have_key('name')
      end
      it 'includes published when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('opt', required_attrs.merge(published: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'opt')
        expect(config).to have_key('published')
      end

      it 'omits published when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'minimal')
        expect(config).not_to have_key('published')
      end
      it 'includes root_instance_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('opt', required_attrs.merge(root_instance_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'opt')
        expect(config).to have_key('root_instance_name')
      end

      it 'omits root_instance_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_app_builder_app', 'minimal')
        expect(config).not_to have_key('root_instance_name')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts published=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(published: val)
          synth.datadog_app_builder_app("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_app_builder_app', "bool_#{val}")
          expect(config['published']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_app_builder_app', 'typed')
        expect(config['app_json']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_app_builder_app('first', required_attrs)
        synth.datadog_app_builder_app('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_app_builder_app')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_app_builder_app,
    method: :datadog_app_builder_app,
    required_attrs: { app_json: 'test-value' },
    expected_outputs: [:id, :action_query_names_to_connection_ids, :description, :name, :published, :root_instance_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:published]
end
