# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_synthetics_concurrency_cap resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogSyntheticsConcurrencyCap do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { on_demand_concurrency_cap: 3.14 } }

  describe ':datadog_synthetics_concurrency_cap' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_concurrency_cap('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_synthetics_concurrency_cap', 'test')
        validate_required_attributes(config, [:on_demand_concurrency_cap])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_synthetics_concurrency_cap('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_synthetics_concurrency_cap)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_synthetics_concurrency_cap('test', required_attrs)

        expect(ref.id).to eq("${datadog_synthetics_concurrency_cap.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_concurrency_cap('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_synthetics_concurrency_cap', 'typed')
        expect(config['on_demand_concurrency_cap']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_concurrency_cap('first', required_attrs)
        synth.datadog_synthetics_concurrency_cap('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_synthetics_concurrency_cap')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_synthetics_concurrency_cap,
    method: :datadog_synthetics_concurrency_cap,
    required_attrs: { on_demand_concurrency_cap: 3.14 },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
