# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_secure_embed_dashboard resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogSecureEmbedDashboard do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { dashboard_id: 'test-value', title: 'test-value' } }

  describe ':datadog_secure_embed_dashboard' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'test')
        validate_required_attributes(config, [:dashboard_id, :title])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_secure_embed_dashboard('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_secure_embed_dashboard)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_secure_embed_dashboard('test', required_attrs)

        expect(ref.id).to eq("${datadog_secure_embed_dashboard.test.id}")
        expect(ref.credential).to eq("${datadog_secure_embed_dashboard.test.credential}")
        expect(ref.global_time_live_span).to eq("${datadog_secure_embed_dashboard.test.global_time_live_span}")
        expect(ref.global_time_selectable).to eq("${datadog_secure_embed_dashboard.test.global_time_selectable}")
        expect(ref.status).to eq("${datadog_secure_embed_dashboard.test.status}")
        expect(ref.token).to eq("${datadog_secure_embed_dashboard.test.token}")
        expect(ref.url).to eq("${datadog_secure_embed_dashboard.test.url}")
        expect(ref.viewing_preferences_high_density).to eq("${datadog_secure_embed_dashboard.test.viewing_preferences_high_density}")
        expect(ref.viewing_preferences_theme).to eq("${datadog_secure_embed_dashboard.test.viewing_preferences_theme}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'test')
        expect(config).not_to have_key('credential')
        expect(config).not_to have_key('global_time_live_span')
        expect(config).not_to have_key('global_time_selectable')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('token')
        expect(config).not_to have_key('url')
        expect(config).not_to have_key('viewing_preferences_high_density')
        expect(config).not_to have_key('viewing_preferences_theme')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ global_time_live_span: 'test-value', global_time_selectable: true, selectable_template_vars: [{ 'key1' => 'val1' }], status: 'test-value', viewing_preferences_high_density: true, viewing_preferences_theme: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'full')
        expect(config).to have_key('global_time_live_span')
        expect(config).to have_key('global_time_selectable')
        expect(config).to have_key('selectable_template_vars')
        expect(config).to have_key('status')
        expect(config).to have_key('viewing_preferences_high_density')
        expect(config).to have_key('viewing_preferences_theme')
      end
    end

    context 'optional attributes' do
      it 'includes global_time_live_span when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('opt', required_attrs.merge(global_time_live_span: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'opt')
        expect(config).to have_key('global_time_live_span')
      end

      it 'omits global_time_live_span when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'minimal')
        expect(config).not_to have_key('global_time_live_span')
      end
      it 'includes global_time_selectable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('opt', required_attrs.merge(global_time_selectable: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'opt')
        expect(config).to have_key('global_time_selectable')
      end

      it 'omits global_time_selectable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'minimal')
        expect(config).not_to have_key('global_time_selectable')
      end
      it 'includes selectable_template_vars when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('opt', required_attrs.merge(selectable_template_vars: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'opt')
        expect(config).to have_key('selectable_template_vars')
      end

      it 'omits selectable_template_vars when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'minimal')
        expect(config).not_to have_key('selectable_template_vars')
      end
      it 'includes status when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('opt', required_attrs.merge(status: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'opt')
        expect(config).to have_key('status')
      end

      it 'omits status when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'minimal')
        expect(config).not_to have_key('status')
      end
      it 'includes viewing_preferences_high_density when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('opt', required_attrs.merge(viewing_preferences_high_density: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'opt')
        expect(config).to have_key('viewing_preferences_high_density')
      end

      it 'omits viewing_preferences_high_density when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'minimal')
        expect(config).not_to have_key('viewing_preferences_high_density')
      end
      it 'includes viewing_preferences_theme when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('opt', required_attrs.merge(viewing_preferences_theme: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'opt')
        expect(config).to have_key('viewing_preferences_theme')
      end

      it 'omits viewing_preferences_theme when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'minimal')
        expect(config).not_to have_key('viewing_preferences_theme')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:credential]
        expect(sensitive_fields).to include(:credential)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts global_time_selectable=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(global_time_selectable: val)
          synth.datadog_secure_embed_dashboard("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', "bool_#{val}")
          expect(config['global_time_selectable']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts viewing_preferences_high_density=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(viewing_preferences_high_density: val)
          synth.datadog_secure_embed_dashboard("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', "bool_#{val}")
          expect(config['viewing_preferences_high_density']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_secure_embed_dashboard', 'typed')
        expect(config['dashboard_id']).to be_a(String)
        expect(config['title']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_secure_embed_dashboard('first', required_attrs)
        synth.datadog_secure_embed_dashboard('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_secure_embed_dashboard')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_secure_embed_dashboard,
    method: :datadog_secure_embed_dashboard,
    required_attrs: { dashboard_id: 'test-value', title: 'test-value' },
    expected_outputs: [:id, :credential, :global_time_live_span, :global_time_selectable, :status, :token, :url, :viewing_preferences_high_density, :viewing_preferences_theme],
    sensitive_fields: [:credential],
    immutable_fields: [],
    boolean_fields: [:global_time_selectable, :viewing_preferences_high_density]
end
