# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_integration_aws_account resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogIntegrationAwsAccount do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { aws_account_id: 'test-value', aws_partition: 'test-value' } }

  describe ':datadog_integration_aws_account' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'test')
        validate_required_attributes(config, [:aws_account_id, :aws_partition])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_aws_account('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_integration_aws_account)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_aws_account('test', required_attrs)

        expect(ref.id).to eq("${datadog_integration_aws_account.test.id}")
        expect(ref.account_tags).to eq("${datadog_integration_aws_account.test.account_tags}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'test')
        expect(config).not_to have_key('account_tags')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ account_tags: ['test-value'], auth_config: { 'key1' => 'val1' }, aws_regions: { 'key1' => 'val1' }, logs_config: { 'key1' => 'val1' }, metrics_config: { 'key1' => 'val1' }, resources_config: { 'key1' => 'val1' }, traces_config: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'full')
        expect(config).to have_key('account_tags')
        expect(config).to have_key('auth_config')
        expect(config).to have_key('aws_regions')
        expect(config).to have_key('logs_config')
        expect(config).to have_key('metrics_config')
        expect(config).to have_key('resources_config')
        expect(config).to have_key('traces_config')
      end
    end

    context 'optional attributes' do
      it 'includes account_tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('opt', required_attrs.merge(account_tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'opt')
        expect(config).to have_key('account_tags')
      end

      it 'omits account_tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'minimal')
        expect(config).not_to have_key('account_tags')
      end
      it 'includes auth_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('opt', required_attrs.merge(auth_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'opt')
        expect(config).to have_key('auth_config')
      end

      it 'omits auth_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'minimal')
        expect(config).not_to have_key('auth_config')
      end
      it 'includes aws_regions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('opt', required_attrs.merge(aws_regions: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'opt')
        expect(config).to have_key('aws_regions')
      end

      it 'omits aws_regions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'minimal')
        expect(config).not_to have_key('aws_regions')
      end
      it 'includes logs_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('opt', required_attrs.merge(logs_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'opt')
        expect(config).to have_key('logs_config')
      end

      it 'omits logs_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'minimal')
        expect(config).not_to have_key('logs_config')
      end
      it 'includes metrics_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('opt', required_attrs.merge(metrics_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'opt')
        expect(config).to have_key('metrics_config')
      end

      it 'omits metrics_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'minimal')
        expect(config).not_to have_key('metrics_config')
      end
      it 'includes resources_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('opt', required_attrs.merge(resources_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'opt')
        expect(config).to have_key('resources_config')
      end

      it 'omits resources_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'minimal')
        expect(config).not_to have_key('resources_config')
      end
      it 'includes traces_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('opt', required_attrs.merge(traces_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'opt')
        expect(config).to have_key('traces_config')
      end

      it 'omits traces_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'minimal')
        expect(config).not_to have_key('traces_config')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_aws_account', 'typed')
        expect(config['aws_account_id']).to be_a(String)
        expect(config['aws_partition']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_aws_account('first', required_attrs)
        synth.datadog_integration_aws_account('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_integration_aws_account')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_integration_aws_account,
    method: :datadog_integration_aws_account,
    required_attrs: { aws_account_id: 'test-value', aws_partition: 'test-value' },
    expected_outputs: [:id, :account_tags],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
