# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_appsec_waf_custom_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogAppsecWafCustomRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { blocking: true, enabled: true, name: 'test-value', tags: { 'key1' => 'val1' } } }

  describe ':datadog_appsec_waf_custom_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'test')
        validate_required_attributes(config, [:blocking, :enabled, :name, :tags])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_appsec_waf_custom_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_appsec_waf_custom_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_appsec_waf_custom_rule('test', required_attrs)

        expect(ref.id).to eq("${datadog_appsec_waf_custom_rule.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ action: { 'key1' => 'val1' }, condition: [{ 'key1' => 'val1' }], path_glob: 'test-value', scope: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'full')
        expect(config).to have_key('action')
        expect(config).to have_key('condition')
        expect(config).to have_key('path_glob')
        expect(config).to have_key('scope')
      end
    end

    context 'optional attributes' do
      it 'includes action when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('opt', required_attrs.merge(action: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'opt')
        expect(config).to have_key('action')
      end

      it 'omits action when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'minimal')
        expect(config).not_to have_key('action')
      end
      it 'includes condition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('opt', required_attrs.merge(condition: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'opt')
        expect(config).to have_key('condition')
      end

      it 'omits condition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'minimal')
        expect(config).not_to have_key('condition')
      end
      it 'includes path_glob when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('opt', required_attrs.merge(path_glob: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'opt')
        expect(config).to have_key('path_glob')
      end

      it 'omits path_glob when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'minimal')
        expect(config).not_to have_key('path_glob')
      end
      it 'includes scope when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('opt', required_attrs.merge(scope: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'opt')
        expect(config).to have_key('scope')
      end

      it 'omits scope when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'minimal')
        expect(config).not_to have_key('scope')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts blocking=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(blocking: val)
          synth.datadog_appsec_waf_custom_rule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', "bool_#{val}")
          expect(config['blocking']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.datadog_appsec_waf_custom_rule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_appsec_waf_custom_rule', 'typed')
        expect([true, false]).to include(config['blocking'])
        expect([true, false]).to include(config['enabled'])
        expect(config['name']).to be_a(String)
        expect(config['tags']).to be_a(Hash)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_appsec_waf_custom_rule('first', required_attrs)
        synth.datadog_appsec_waf_custom_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_appsec_waf_custom_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_appsec_waf_custom_rule,
    method: :datadog_appsec_waf_custom_rule,
    required_attrs: { blocking: true, enabled: true, name: 'test-value', tags: { 'key1' => 'val1' } },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:blocking, :enabled]
end
