# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_integration_gcp_sts resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogIntegrationGcpSts do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { client_email: 'test-value' } }

  describe ':datadog_integration_gcp_sts' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'test')
        validate_required_attributes(config, [:client_email])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_gcp_sts('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_integration_gcp_sts)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_gcp_sts('test', required_attrs)

        expect(ref.id).to eq("${datadog_integration_gcp_sts.test.id}")
        expect(ref.automute).to eq("${datadog_integration_gcp_sts.test.automute}")
        expect(ref.cloud_run_revision_filters).to eq("${datadog_integration_gcp_sts.test.cloud_run_revision_filters}")
        expect(ref.delegate_account_email).to eq("${datadog_integration_gcp_sts.test.delegate_account_email}")
        expect(ref.host_filters).to eq("${datadog_integration_gcp_sts.test.host_filters}")
        expect(ref.is_cspm_enabled).to eq("${datadog_integration_gcp_sts.test.is_cspm_enabled}")
        expect(ref.is_global_location_enabled).to eq("${datadog_integration_gcp_sts.test.is_global_location_enabled}")
        expect(ref.is_per_project_quota_enabled).to eq("${datadog_integration_gcp_sts.test.is_per_project_quota_enabled}")
        expect(ref.is_resource_change_collection_enabled).to eq("${datadog_integration_gcp_sts.test.is_resource_change_collection_enabled}")
        expect(ref.is_security_command_center_enabled).to eq("${datadog_integration_gcp_sts.test.is_security_command_center_enabled}")
        expect(ref.metric_namespace_configs).to eq("${datadog_integration_gcp_sts.test.metric_namespace_configs}")
        expect(ref.monitored_resource_configs).to eq("${datadog_integration_gcp_sts.test.monitored_resource_configs}")
        expect(ref.resource_collection_enabled).to eq("${datadog_integration_gcp_sts.test.resource_collection_enabled}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'test')
        expect(config).not_to have_key('automute')
        expect(config).not_to have_key('cloud_run_revision_filters')
        expect(config).not_to have_key('delegate_account_email')
        expect(config).not_to have_key('host_filters')
        expect(config).not_to have_key('is_cspm_enabled')
        expect(config).not_to have_key('is_global_location_enabled')
        expect(config).not_to have_key('is_per_project_quota_enabled')
        expect(config).not_to have_key('is_resource_change_collection_enabled')
        expect(config).not_to have_key('is_security_command_center_enabled')
        expect(config).not_to have_key('metric_namespace_configs')
        expect(config).not_to have_key('monitored_resource_configs')
        expect(config).not_to have_key('resource_collection_enabled')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ account_tags: ['test-value'], automute: true, cloud_run_revision_filters: ['test-value'], host_filters: ['test-value'], is_cspm_enabled: true, is_global_location_enabled: true, is_per_project_quota_enabled: true, is_resource_change_collection_enabled: true, is_security_command_center_enabled: true, metric_namespace_configs: [{ 'key1' => 'val1' }], monitored_resource_configs: [{ 'key1' => 'val1' }], region_filter_configs: ['test-value'], resource_collection_enabled: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'full')
        expect(config).to have_key('account_tags')
        expect(config).to have_key('automute')
        expect(config).to have_key('cloud_run_revision_filters')
        expect(config).to have_key('host_filters')
        expect(config).to have_key('is_cspm_enabled')
        expect(config).to have_key('is_global_location_enabled')
        expect(config).to have_key('is_per_project_quota_enabled')
        expect(config).to have_key('is_resource_change_collection_enabled')
        expect(config).to have_key('is_security_command_center_enabled')
        expect(config).to have_key('metric_namespace_configs')
        expect(config).to have_key('monitored_resource_configs')
        expect(config).to have_key('region_filter_configs')
        expect(config).to have_key('resource_collection_enabled')
      end
    end

    context 'optional attributes' do
      it 'includes account_tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(account_tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('account_tags')
      end

      it 'omits account_tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('account_tags')
      end
      it 'includes automute when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(automute: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('automute')
      end

      it 'omits automute when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('automute')
      end
      it 'includes cloud_run_revision_filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(cloud_run_revision_filters: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('cloud_run_revision_filters')
      end

      it 'omits cloud_run_revision_filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('cloud_run_revision_filters')
      end
      it 'includes host_filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(host_filters: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('host_filters')
      end

      it 'omits host_filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('host_filters')
      end
      it 'includes is_cspm_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(is_cspm_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('is_cspm_enabled')
      end

      it 'omits is_cspm_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('is_cspm_enabled')
      end
      it 'includes is_global_location_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(is_global_location_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('is_global_location_enabled')
      end

      it 'omits is_global_location_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('is_global_location_enabled')
      end
      it 'includes is_per_project_quota_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(is_per_project_quota_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('is_per_project_quota_enabled')
      end

      it 'omits is_per_project_quota_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('is_per_project_quota_enabled')
      end
      it 'includes is_resource_change_collection_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(is_resource_change_collection_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('is_resource_change_collection_enabled')
      end

      it 'omits is_resource_change_collection_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('is_resource_change_collection_enabled')
      end
      it 'includes is_security_command_center_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(is_security_command_center_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('is_security_command_center_enabled')
      end

      it 'omits is_security_command_center_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('is_security_command_center_enabled')
      end
      it 'includes metric_namespace_configs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(metric_namespace_configs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('metric_namespace_configs')
      end

      it 'omits metric_namespace_configs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('metric_namespace_configs')
      end
      it 'includes monitored_resource_configs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(monitored_resource_configs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('monitored_resource_configs')
      end

      it 'omits monitored_resource_configs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('monitored_resource_configs')
      end
      it 'includes region_filter_configs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(region_filter_configs: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('region_filter_configs')
      end

      it 'omits region_filter_configs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('region_filter_configs')
      end
      it 'includes resource_collection_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('opt', required_attrs.merge(resource_collection_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'opt')
        expect(config).to have_key('resource_collection_enabled')
      end

      it 'omits resource_collection_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'minimal')
        expect(config).not_to have_key('resource_collection_enabled')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts automute=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(automute: val)
          synth.datadog_integration_gcp_sts("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp_sts', "bool_#{val}")
          expect(config['automute']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_cspm_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_cspm_enabled: val)
          synth.datadog_integration_gcp_sts("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp_sts', "bool_#{val}")
          expect(config['is_cspm_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_global_location_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_global_location_enabled: val)
          synth.datadog_integration_gcp_sts("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp_sts', "bool_#{val}")
          expect(config['is_global_location_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_per_project_quota_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_per_project_quota_enabled: val)
          synth.datadog_integration_gcp_sts("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp_sts', "bool_#{val}")
          expect(config['is_per_project_quota_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_resource_change_collection_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_resource_change_collection_enabled: val)
          synth.datadog_integration_gcp_sts("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp_sts', "bool_#{val}")
          expect(config['is_resource_change_collection_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_security_command_center_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_security_command_center_enabled: val)
          synth.datadog_integration_gcp_sts("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp_sts', "bool_#{val}")
          expect(config['is_security_command_center_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts resource_collection_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(resource_collection_enabled: val)
          synth.datadog_integration_gcp_sts("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_gcp_sts', "bool_#{val}")
          expect(config['resource_collection_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_gcp_sts', 'typed')
        expect(config['client_email']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_gcp_sts('first', required_attrs)
        synth.datadog_integration_gcp_sts('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_integration_gcp_sts')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_integration_gcp_sts,
    method: :datadog_integration_gcp_sts,
    required_attrs: { client_email: 'test-value' },
    expected_outputs: [:id, :automute, :cloud_run_revision_filters, :delegate_account_email, :host_filters, :is_cspm_enabled, :is_global_location_enabled, :is_per_project_quota_enabled, :is_resource_change_collection_enabled, :is_security_command_center_enabled, :metric_namespace_configs, :monitored_resource_configs, :resource_collection_enabled],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:automute, :is_cspm_enabled, :is_global_location_enabled, :is_per_project_quota_enabled, :is_resource_change_collection_enabled, :is_security_command_center_enabled, :resource_collection_enabled]
end
