# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_synthetics_suite resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogSyntheticsSuite do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':datadog_synthetics_suite' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_synthetics_suite('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_synthetics_suite)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_synthetics_suite('test', required_attrs)

        expect(ref.id).to eq("${datadog_synthetics_suite.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ message: 'test-value', options: [{ 'key1' => 'val1' }], tags: ['test-value'], tests: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'full')
        expect(config).to have_key('message')
        expect(config).to have_key('options')
        expect(config).to have_key('tags')
        expect(config).to have_key('tests')
      end
    end

    context 'optional attributes' do
      it 'includes message when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('opt', required_attrs.merge(message: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'opt')
        expect(config).to have_key('message')
      end

      it 'omits message when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'minimal')
        expect(config).not_to have_key('message')
      end
      it 'includes options when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('opt', required_attrs.merge(options: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'opt')
        expect(config).to have_key('options')
      end

      it 'omits options when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'minimal')
        expect(config).not_to have_key('options')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes tests when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('opt', required_attrs.merge(tests: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'opt')
        expect(config).to have_key('tests')
      end

      it 'omits tests when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'minimal')
        expect(config).not_to have_key('tests')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_synthetics_suite', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_synthetics_suite('first', required_attrs)
        synth.datadog_synthetics_suite('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_synthetics_suite')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_synthetics_suite,
    method: :datadog_synthetics_suite,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
