# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_powerpack resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogPowerpack do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':datadog_powerpack' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_powerpack', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_powerpack('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_powerpack)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_powerpack('test', required_attrs)

        expect(ref.id).to eq("${datadog_powerpack.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', layout: { 'key1' => 'val1' }, live_span: 'test-value', name: 'test-value', show_title: true, tags: ['test-value'], template_variables: [{ 'key1' => 'val1' }], widget: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_powerpack', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('layout')
        expect(config).to have_key('live_span')
        expect(config).to have_key('name')
        expect(config).to have_key('show_title')
        expect(config).to have_key('tags')
        expect(config).to have_key('template_variables')
        expect(config).to have_key('widget')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes layout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('opt', required_attrs.merge(layout: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'opt')
        expect(config).to have_key('layout')
      end

      it 'omits layout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'minimal')
        expect(config).not_to have_key('layout')
      end
      it 'includes live_span when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('opt', required_attrs.merge(live_span: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'opt')
        expect(config).to have_key('live_span')
      end

      it 'omits live_span when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'minimal')
        expect(config).not_to have_key('live_span')
      end
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'minimal')
        expect(config).not_to have_key('name')
      end
      it 'includes show_title when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('opt', required_attrs.merge(show_title: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'opt')
        expect(config).to have_key('show_title')
      end

      it 'omits show_title when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'minimal')
        expect(config).not_to have_key('show_title')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes template_variables when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('opt', required_attrs.merge(template_variables: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'opt')
        expect(config).to have_key('template_variables')
      end

      it 'omits template_variables when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'minimal')
        expect(config).not_to have_key('template_variables')
      end
      it 'includes widget when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('opt', required_attrs.merge(widget: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'opt')
        expect(config).to have_key('widget')
      end

      it 'omits widget when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_powerpack', 'minimal')
        expect(config).not_to have_key('widget')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts show_title=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(show_title: val)
          synth.datadog_powerpack("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_powerpack', "bool_#{val}")
          expect(config['show_title']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_powerpack', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_powerpack('first', required_attrs)
        synth.datadog_powerpack('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_powerpack')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_powerpack,
    method: :datadog_powerpack,
    required_attrs: {},
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:show_title]
end
