# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_cost_budget resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogCostBudget do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { end_month: 3.14, metrics_query: 'test-value', name: 'test-value', start_month: 3.14 } }

  describe ':datadog_cost_budget' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_cost_budget('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_cost_budget', 'test')
        validate_required_attributes(config, [:end_month, :metrics_query, :name, :start_month])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_cost_budget('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_cost_budget)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_cost_budget('test', required_attrs)

        expect(ref.id).to eq("${datadog_cost_budget.test.id}")
        expect(ref.total_amount).to eq("${datadog_cost_budget.test.total_amount}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_cost_budget('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_cost_budget', 'test')
        expect(config).not_to have_key('total_amount')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ budget_line: [{ 'key1' => 'val1' }], entries: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_cost_budget('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_cost_budget', 'full')
        expect(config).to have_key('budget_line')
        expect(config).to have_key('entries')
      end
    end

    context 'optional attributes' do
      it 'includes budget_line when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_cost_budget('opt', required_attrs.merge(budget_line: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_cost_budget', 'opt')
        expect(config).to have_key('budget_line')
      end

      it 'omits budget_line when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_cost_budget('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_cost_budget', 'minimal')
        expect(config).not_to have_key('budget_line')
      end
      it 'includes entries when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_cost_budget('opt', required_attrs.merge(entries: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_cost_budget', 'opt')
        expect(config).to have_key('entries')
      end

      it 'omits entries when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_cost_budget('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_cost_budget', 'minimal')
        expect(config).not_to have_key('entries')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_cost_budget('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_cost_budget', 'typed')
        expect(config['end_month']).to be_a(Float)
        expect(config['metrics_query']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['start_month']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_cost_budget('first', required_attrs)
        synth.datadog_cost_budget('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_cost_budget')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_cost_budget,
    method: :datadog_cost_budget,
    required_attrs: { end_month: 3.14, metrics_query: 'test-value', name: 'test-value', start_month: 3.14 },
    expected_outputs: [:id, :total_amount],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
