# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_webhook resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogWebhook do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', url: 'test-value' } }

  describe ':datadog_webhook' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_webhook', 'test')
        validate_required_attributes(config, [:name, :url])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_webhook('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_webhook)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_webhook('test', required_attrs)

        expect(ref.id).to eq("${datadog_webhook.test.id}")
        expect(ref.encode_as).to eq("${datadog_webhook.test.encode_as}")
        expect(ref.payload).to eq("${datadog_webhook.test.payload}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_webhook', 'test')
        expect(config).not_to have_key('encode_as')
        expect(config).not_to have_key('payload')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_headers: 'test-value', encode_as: 'test-value', payload: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_webhook', 'full')
        expect(config).to have_key('custom_headers')
        expect(config).to have_key('encode_as')
        expect(config).to have_key('payload')
      end
    end

    context 'optional attributes' do
      it 'includes custom_headers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('opt', required_attrs.merge(custom_headers: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_webhook', 'opt')
        expect(config).to have_key('custom_headers')
      end

      it 'omits custom_headers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_webhook', 'minimal')
        expect(config).not_to have_key('custom_headers')
      end
      it 'includes encode_as when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('opt', required_attrs.merge(encode_as: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_webhook', 'opt')
        expect(config).to have_key('encode_as')
      end

      it 'omits encode_as when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_webhook', 'minimal')
        expect(config).not_to have_key('encode_as')
      end
      it 'includes payload when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('opt', required_attrs.merge(payload: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_webhook', 'opt')
        expect(config).to have_key('payload')
      end

      it 'omits payload when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_webhook', 'minimal')
        expect(config).not_to have_key('payload')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_webhook', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['url']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook('first', required_attrs)
        synth.datadog_webhook('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_webhook')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_webhook,
    method: :datadog_webhook,
    required_attrs: { name: 'test-value', url: 'test-value' },
    expected_outputs: [:id, :encode_as, :payload],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
