# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_on_call_schedule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogOnCallSchedule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', time_zone: 'test-value' } }

  describe ':datadog_on_call_schedule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_schedule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_on_call_schedule', 'test')
        validate_required_attributes(config, [:name, :time_zone])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_on_call_schedule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_on_call_schedule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_on_call_schedule('test', required_attrs)

        expect(ref.id).to eq("${datadog_on_call_schedule.test.id}")
        expect(ref.teams).to eq("${datadog_on_call_schedule.test.teams}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_schedule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_on_call_schedule', 'test')
        expect(config).not_to have_key('teams')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ layer: [{ 'key1' => 'val1' }], teams: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_schedule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_on_call_schedule', 'full')
        expect(config).to have_key('layer')
        expect(config).to have_key('teams')
      end
    end

    context 'optional attributes' do
      it 'includes layer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_schedule('opt', required_attrs.merge(layer: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_on_call_schedule', 'opt')
        expect(config).to have_key('layer')
      end

      it 'omits layer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_on_call_schedule', 'minimal')
        expect(config).not_to have_key('layer')
      end
      it 'includes teams when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_schedule('opt', required_attrs.merge(teams: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_on_call_schedule', 'opt')
        expect(config).to have_key('teams')
      end

      it 'omits teams when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_on_call_schedule', 'minimal')
        expect(config).not_to have_key('teams')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_schedule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_on_call_schedule', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['time_zone']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_schedule('first', required_attrs)
        synth.datadog_on_call_schedule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_on_call_schedule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_on_call_schedule,
    method: :datadog_on_call_schedule,
    required_attrs: { name: 'test-value', time_zone: 'test-value' },
    expected_outputs: [:id, :teams],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
