# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_datastore resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogDatastore do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', primary_column_name: 'test-value' } }

  describe ':datadog_datastore' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_datastore', 'test')
        validate_required_attributes(config, [:name, :primary_column_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_datastore('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_datastore)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_datastore('test', required_attrs)

        expect(ref.id).to eq("${datadog_datastore.test.id}")
        expect(ref.created_at).to eq("${datadog_datastore.test.created_at}")
        expect(ref.creator_user_id).to eq("${datadog_datastore.test.creator_user_id}")
        expect(ref.creator_user_uuid).to eq("${datadog_datastore.test.creator_user_uuid}")
        expect(ref.modified_at).to eq("${datadog_datastore.test.modified_at}")
        expect(ref.org_id).to eq("${datadog_datastore.test.org_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_datastore', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('creator_user_id')
        expect(config).not_to have_key('creator_user_uuid')
        expect(config).not_to have_key('modified_at')
        expect(config).not_to have_key('org_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', org_access: 'test-value', primary_key_generation_strategy: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_datastore', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('org_access')
        expect(config).to have_key('primary_key_generation_strategy')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_datastore', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_datastore', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes org_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('opt', required_attrs.merge(org_access: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_datastore', 'opt')
        expect(config).to have_key('org_access')
      end

      it 'omits org_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_datastore', 'minimal')
        expect(config).not_to have_key('org_access')
      end
      it 'includes primary_key_generation_strategy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('opt', required_attrs.merge(primary_key_generation_strategy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_datastore', 'opt')
        expect(config).to have_key('primary_key_generation_strategy')
      end

      it 'omits primary_key_generation_strategy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_datastore', 'minimal')
        expect(config).not_to have_key('primary_key_generation_strategy')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_datastore', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['primary_column_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_datastore('first', required_attrs)
        synth.datadog_datastore('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_datastore')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_datastore,
    method: :datadog_datastore,
    required_attrs: { name: 'test-value', primary_column_name: 'test-value' },
    expected_outputs: [:id, :created_at, :creator_user_id, :creator_user_uuid, :modified_at, :org_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
