# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_metric_metadata resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogMetricMetadata do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metric: 'test-value' } }

  describe ':datadog_metric_metadata' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'test')
        validate_required_attributes(config, [:metric])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_metric_metadata('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_metric_metadata)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_metric_metadata('test', required_attrs)

        expect(ref.id).to eq("${datadog_metric_metadata.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', per_unit: 'test-value', short_name: 'test-value', statsd_interval: 3.14, type: 'test-value', unit: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_metric_metadata', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('per_unit')
        expect(config).to have_key('short_name')
        expect(config).to have_key('statsd_interval')
        expect(config).to have_key('type')
        expect(config).to have_key('unit')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes per_unit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('opt', required_attrs.merge(per_unit: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'opt')
        expect(config).to have_key('per_unit')
      end

      it 'omits per_unit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'minimal')
        expect(config).not_to have_key('per_unit')
      end
      it 'includes short_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('opt', required_attrs.merge(short_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'opt')
        expect(config).to have_key('short_name')
      end

      it 'omits short_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'minimal')
        expect(config).not_to have_key('short_name')
      end
      it 'includes statsd_interval when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('opt', required_attrs.merge(statsd_interval: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'opt')
        expect(config).to have_key('statsd_interval')
      end

      it 'omits statsd_interval when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'minimal')
        expect(config).not_to have_key('statsd_interval')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'minimal')
        expect(config).not_to have_key('type')
      end
      it 'includes unit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('opt', required_attrs.merge(unit: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'opt')
        expect(config).to have_key('unit')
      end

      it 'omits unit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_metric_metadata', 'minimal')
        expect(config).not_to have_key('unit')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_metric_metadata', 'typed')
        expect(config['metric']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_metric_metadata('first', required_attrs)
        synth.datadog_metric_metadata('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_metric_metadata')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_metric_metadata,
    method: :datadog_metric_metadata,
    required_attrs: { metric: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
