# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_integration_azure resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogIntegrationAzure do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { client_id: 'test-value', client_secret: 'test-value', tenant_name: 'test-value' } }

  describe ':datadog_integration_azure' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'test')
        validate_required_attributes(config, [:client_id, :client_secret, :tenant_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_azure('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_integration_azure)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_azure('test', required_attrs)

        expect(ref.id).to eq("${datadog_integration_azure.test.id}")
        expect(ref.app_service_plan_filters).to eq("${datadog_integration_azure.test.app_service_plan_filters}")
        expect(ref.automute).to eq("${datadog_integration_azure.test.automute}")
        expect(ref.container_app_filters).to eq("${datadog_integration_azure.test.container_app_filters}")
        expect(ref.cspm_enabled).to eq("${datadog_integration_azure.test.cspm_enabled}")
        expect(ref.custom_metrics_enabled).to eq("${datadog_integration_azure.test.custom_metrics_enabled}")
        expect(ref.host_filters).to eq("${datadog_integration_azure.test.host_filters}")
        expect(ref.metrics_enabled).to eq("${datadog_integration_azure.test.metrics_enabled}")
        expect(ref.metrics_enabled_default).to eq("${datadog_integration_azure.test.metrics_enabled_default}")
        expect(ref.resource_collection_enabled).to eq("${datadog_integration_azure.test.resource_collection_enabled}")
        expect(ref.resource_provider_configs).to eq("${datadog_integration_azure.test.resource_provider_configs}")
        expect(ref.usage_metrics_enabled).to eq("${datadog_integration_azure.test.usage_metrics_enabled}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_azure', 'test')
        expect(config).not_to have_key('app_service_plan_filters')
        expect(config).not_to have_key('automute')
        expect(config).not_to have_key('container_app_filters')
        expect(config).not_to have_key('cspm_enabled')
        expect(config).not_to have_key('custom_metrics_enabled')
        expect(config).not_to have_key('host_filters')
        expect(config).not_to have_key('metrics_enabled')
        expect(config).not_to have_key('metrics_enabled_default')
        expect(config).not_to have_key('resource_collection_enabled')
        expect(config).not_to have_key('resource_provider_configs')
        expect(config).not_to have_key('usage_metrics_enabled')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ app_service_plan_filters: 'test-value', automute: true, container_app_filters: 'test-value', cspm_enabled: true, custom_metrics_enabled: true, host_filters: 'test-value', metrics_enabled: true, metrics_enabled_default: true, resource_collection_enabled: true, resource_provider_configs: [{ 'key1' => 'val1' }], usage_metrics_enabled: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_azure', 'full')
        expect(config).to have_key('app_service_plan_filters')
        expect(config).to have_key('automute')
        expect(config).to have_key('container_app_filters')
        expect(config).to have_key('cspm_enabled')
        expect(config).to have_key('custom_metrics_enabled')
        expect(config).to have_key('host_filters')
        expect(config).to have_key('metrics_enabled')
        expect(config).to have_key('metrics_enabled_default')
        expect(config).to have_key('resource_collection_enabled')
        expect(config).to have_key('resource_provider_configs')
        expect(config).to have_key('usage_metrics_enabled')
      end
    end

    context 'optional attributes' do
      it 'includes app_service_plan_filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(app_service_plan_filters: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('app_service_plan_filters')
      end

      it 'omits app_service_plan_filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('app_service_plan_filters')
      end
      it 'includes automute when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(automute: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('automute')
      end

      it 'omits automute when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('automute')
      end
      it 'includes container_app_filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(container_app_filters: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('container_app_filters')
      end

      it 'omits container_app_filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('container_app_filters')
      end
      it 'includes cspm_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(cspm_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('cspm_enabled')
      end

      it 'omits cspm_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('cspm_enabled')
      end
      it 'includes custom_metrics_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(custom_metrics_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('custom_metrics_enabled')
      end

      it 'omits custom_metrics_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('custom_metrics_enabled')
      end
      it 'includes host_filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(host_filters: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('host_filters')
      end

      it 'omits host_filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('host_filters')
      end
      it 'includes metrics_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(metrics_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('metrics_enabled')
      end

      it 'omits metrics_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('metrics_enabled')
      end
      it 'includes metrics_enabled_default when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(metrics_enabled_default: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('metrics_enabled_default')
      end

      it 'omits metrics_enabled_default when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('metrics_enabled_default')
      end
      it 'includes resource_collection_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(resource_collection_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('resource_collection_enabled')
      end

      it 'omits resource_collection_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('resource_collection_enabled')
      end
      it 'includes resource_provider_configs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(resource_provider_configs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('resource_provider_configs')
      end

      it 'omits resource_provider_configs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('resource_provider_configs')
      end
      it 'includes usage_metrics_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('opt', required_attrs.merge(usage_metrics_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'opt')
        expect(config).to have_key('usage_metrics_enabled')
      end

      it 'omits usage_metrics_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_azure', 'minimal')
        expect(config).not_to have_key('usage_metrics_enabled')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:client_secret]
        expect(sensitive_fields).to include(:client_secret)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts automute=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(automute: val)
          synth.datadog_integration_azure("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_azure', "bool_#{val}")
          expect(config['automute']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts cspm_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(cspm_enabled: val)
          synth.datadog_integration_azure("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_azure', "bool_#{val}")
          expect(config['cspm_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts custom_metrics_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(custom_metrics_enabled: val)
          synth.datadog_integration_azure("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_azure', "bool_#{val}")
          expect(config['custom_metrics_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts metrics_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(metrics_enabled: val)
          synth.datadog_integration_azure("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_azure', "bool_#{val}")
          expect(config['metrics_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts metrics_enabled_default=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(metrics_enabled_default: val)
          synth.datadog_integration_azure("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_azure', "bool_#{val}")
          expect(config['metrics_enabled_default']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts resource_collection_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(resource_collection_enabled: val)
          synth.datadog_integration_azure("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_azure', "bool_#{val}")
          expect(config['resource_collection_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts usage_metrics_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(usage_metrics_enabled: val)
          synth.datadog_integration_azure("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_integration_azure', "bool_#{val}")
          expect(config['usage_metrics_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_azure', 'typed')
        expect(config['client_id']).to be_a(String)
        expect(config['client_secret']).to be_a(String)
        expect(config['tenant_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_azure('first', required_attrs)
        synth.datadog_integration_azure('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_integration_azure')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_integration_azure,
    method: :datadog_integration_azure,
    required_attrs: { client_id: 'test-value', client_secret: 'test-value', tenant_name: 'test-value' },
    expected_outputs: [:id, :app_service_plan_filters, :automute, :container_app_filters, :cspm_enabled, :custom_metrics_enabled, :host_filters, :metrics_enabled, :metrics_enabled_default, :resource_collection_enabled, :resource_provider_configs, :usage_metrics_enabled],
    sensitive_fields: [:client_secret],
    immutable_fields: [],
    boolean_fields: [:automute, :cspm_enabled, :custom_metrics_enabled, :metrics_enabled, :metrics_enabled_default, :resource_collection_enabled, :usage_metrics_enabled]
end
