# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_integration_fastly_service resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogIntegrationFastlyService do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { service_id: 'test-value' } }

  describe ':datadog_integration_fastly_service' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_fastly_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_integration_fastly_service', 'test')
        validate_required_attributes(config, [:service_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_fastly_service('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_integration_fastly_service)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_integration_fastly_service('test', required_attrs)

        expect(ref.id).to eq("${datadog_integration_fastly_service.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ account_id: 'test-value', tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_fastly_service('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_fastly_service', 'full')
        expect(config).to have_key('account_id')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes account_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_fastly_service('opt', required_attrs.merge(account_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_fastly_service', 'opt')
        expect(config).to have_key('account_id')
      end

      it 'omits account_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_fastly_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_fastly_service', 'minimal')
        expect(config).not_to have_key('account_id')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_fastly_service('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_fastly_service', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_fastly_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_integration_fastly_service', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_fastly_service('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_integration_fastly_service', 'typed')
        expect(config['service_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_integration_fastly_service('first', required_attrs)
        synth.datadog_integration_fastly_service('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_integration_fastly_service')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_integration_fastly_service,
    method: :datadog_integration_fastly_service,
    required_attrs: { service_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
