# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_csm_threats_agent_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogCsmThreatsAgentRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { expression: 'test-value', name: 'test-value' } }

  describe ':datadog_csm_threats_agent_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'test')
        validate_required_attributes(config, [:expression, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_csm_threats_agent_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_csm_threats_agent_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_csm_threats_agent_rule('test', required_attrs)

        expect(ref.id).to eq("${datadog_csm_threats_agent_rule.test.id}")
        expect(ref.description).to eq("${datadog_csm_threats_agent_rule.test.description}")
        expect(ref.enabled).to eq("${datadog_csm_threats_agent_rule.test.enabled}")
        expect(ref.product_tags).to eq("${datadog_csm_threats_agent_rule.test.product_tags}")
        expect(ref.silent).to eq("${datadog_csm_threats_agent_rule.test.silent}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'test')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('product_tags')
        expect(config).not_to have_key('silent')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ actions: [{ 'key1' => 'val1' }], description: 'test-value', enabled: true, policy_id: 'test-value', product_tags: ['test-value'], silent: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'full')
        expect(config).to have_key('actions')
        expect(config).to have_key('description')
        expect(config).to have_key('enabled')
        expect(config).to have_key('policy_id')
        expect(config).to have_key('product_tags')
        expect(config).to have_key('silent')
      end
    end

    context 'optional attributes' do
      it 'includes actions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('opt', required_attrs.merge(actions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'opt')
        expect(config).to have_key('actions')
      end

      it 'omits actions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'minimal')
        expect(config).not_to have_key('actions')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes policy_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('opt', required_attrs.merge(policy_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'opt')
        expect(config).to have_key('policy_id')
      end

      it 'omits policy_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'minimal')
        expect(config).not_to have_key('policy_id')
      end
      it 'includes product_tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('opt', required_attrs.merge(product_tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'opt')
        expect(config).to have_key('product_tags')
      end

      it 'omits product_tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'minimal')
        expect(config).not_to have_key('product_tags')
      end
      it 'includes silent when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('opt', required_attrs.merge(silent: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'opt')
        expect(config).to have_key('silent')
      end

      it 'omits silent when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'minimal')
        expect(config).not_to have_key('silent')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.datadog_csm_threats_agent_rule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts silent=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(silent: val)
          synth.datadog_csm_threats_agent_rule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', "bool_#{val}")
          expect(config['silent']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_csm_threats_agent_rule', 'typed')
        expect(config['expression']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_csm_threats_agent_rule('first', required_attrs)
        synth.datadog_csm_threats_agent_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_csm_threats_agent_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_csm_threats_agent_rule,
    method: :datadog_csm_threats_agent_rule,
    required_attrs: { expression: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :description, :enabled, :product_tags, :silent],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled, :silent]
end
