# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':datadog_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_role', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_role('test', required_attrs)

        expect(ref.id).to eq("${datadog_role.test.id}")
        expect(ref.user_count).to eq("${datadog_role.test.user_count}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_role', 'test')
        expect(config).not_to have_key('user_count')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ default_permissions_opt_out: true, permission: [{ 'key1' => 'val1' }], validate: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_role', 'full')
        expect(config).to have_key('default_permissions_opt_out')
        expect(config).to have_key('permission')
        expect(config).to have_key('validate')
      end
    end

    context 'optional attributes' do
      it 'includes default_permissions_opt_out when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('opt', required_attrs.merge(default_permissions_opt_out: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_role', 'opt')
        expect(config).to have_key('default_permissions_opt_out')
      end

      it 'omits default_permissions_opt_out when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_role', 'minimal')
        expect(config).not_to have_key('default_permissions_opt_out')
      end
      it 'includes permission when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('opt', required_attrs.merge(permission: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_role', 'opt')
        expect(config).to have_key('permission')
      end

      it 'omits permission when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_role', 'minimal')
        expect(config).not_to have_key('permission')
      end
      it 'includes validate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('opt', required_attrs.merge(validate: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_role', 'opt')
        expect(config).to have_key('validate')
      end

      it 'omits validate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_role', 'minimal')
        expect(config).not_to have_key('validate')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts default_permissions_opt_out=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(default_permissions_opt_out: val)
          synth.datadog_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_role', "bool_#{val}")
          expect(config['default_permissions_opt_out']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts validate=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(validate: val)
          synth.datadog_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_role', "bool_#{val}")
          expect(config['validate']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_role', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_role('first', required_attrs)
        synth.datadog_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_role,
    method: :datadog_role,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :user_count],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:default_permissions_opt_out, :validate]
end
