# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_custom_allocation_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogCustomAllocationRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { enabled: true, providernames: ['test-value'], rule_name: 'test-value' } }

  describe ':datadog_custom_allocation_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_custom_allocation_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_custom_allocation_rule', 'test')
        validate_required_attributes(config, [:enabled, :providernames, :rule_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_custom_allocation_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_custom_allocation_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_custom_allocation_rule('test', required_attrs)

        expect(ref.id).to eq("${datadog_custom_allocation_rule.test.id}")
        expect(ref.created).to eq("${datadog_custom_allocation_rule.test.created}")
        expect(ref.last_modified_user_uuid).to eq("${datadog_custom_allocation_rule.test.last_modified_user_uuid}")
        expect(ref.order_id).to eq("${datadog_custom_allocation_rule.test.order_id}")
        expect(ref.rejected).to eq("${datadog_custom_allocation_rule.test.rejected}")
        expect(ref.updated).to eq("${datadog_custom_allocation_rule.test.updated}")
        expect(ref.version).to eq("${datadog_custom_allocation_rule.test.version}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_custom_allocation_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_custom_allocation_rule', 'test')
        expect(config).not_to have_key('created')
        expect(config).not_to have_key('last_modified_user_uuid')
        expect(config).not_to have_key('order_id')
        expect(config).not_to have_key('rejected')
        expect(config).not_to have_key('updated')
        expect(config).not_to have_key('version')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ costs_to_allocate: [{ 'key1' => 'val1' }], strategy: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_custom_allocation_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_custom_allocation_rule', 'full')
        expect(config).to have_key('costs_to_allocate')
        expect(config).to have_key('strategy')
      end
    end

    context 'optional attributes' do
      it 'includes costs_to_allocate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_custom_allocation_rule('opt', required_attrs.merge(costs_to_allocate: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_custom_allocation_rule', 'opt')
        expect(config).to have_key('costs_to_allocate')
      end

      it 'omits costs_to_allocate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_custom_allocation_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_custom_allocation_rule', 'minimal')
        expect(config).not_to have_key('costs_to_allocate')
      end
      it 'includes strategy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_custom_allocation_rule('opt', required_attrs.merge(strategy: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_custom_allocation_rule', 'opt')
        expect(config).to have_key('strategy')
      end

      it 'omits strategy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_custom_allocation_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_custom_allocation_rule', 'minimal')
        expect(config).not_to have_key('strategy')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.datadog_custom_allocation_rule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_custom_allocation_rule', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_custom_allocation_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_custom_allocation_rule', 'typed')
        expect([true, false]).to include(config['enabled'])
        expect(config['providernames']).to be_a(Array)
        expect(config['rule_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_custom_allocation_rule('first', required_attrs)
        synth.datadog_custom_allocation_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_custom_allocation_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_custom_allocation_rule,
    method: :datadog_custom_allocation_rule,
    required_attrs: { enabled: true, providernames: ['test-value'], rule_name: 'test-value' },
    expected_outputs: [:id, :created, :last_modified_user_uuid, :order_id, :rejected, :updated, :version],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
