# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_webhook_custom_variable resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogWebhookCustomVariable do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { is_secret: true, name: 'test-value', value: 'test-value' } }

  describe ':datadog_webhook_custom_variable' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook_custom_variable('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_webhook_custom_variable', 'test')
        validate_required_attributes(config, [:is_secret, :name, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_webhook_custom_variable('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_webhook_custom_variable)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_webhook_custom_variable('test', required_attrs)

        expect(ref.id).to eq("${datadog_webhook_custom_variable.test.id}")
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:value]
        expect(sensitive_fields).to include(:value)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts is_secret=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_secret: val)
          synth.datadog_webhook_custom_variable("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_webhook_custom_variable', "bool_#{val}")
          expect(config['is_secret']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook_custom_variable('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_webhook_custom_variable', 'typed')
        expect([true, false]).to include(config['is_secret'])
        expect(config['name']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_webhook_custom_variable('first', required_attrs)
        synth.datadog_webhook_custom_variable('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_webhook_custom_variable')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_webhook_custom_variable,
    method: :datadog_webhook_custom_variable,
    required_attrs: { is_secret: true, name: 'test-value', value: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [:value],
    immutable_fields: [],
    boolean_fields: [:is_secret]
end
