# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_on_call_user_notification_channel resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogOnCallUserNotificationChannel do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { user_id: 'test-value' } }

  describe ':datadog_on_call_user_notification_channel' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_user_notification_channel('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_on_call_user_notification_channel', 'test')
        validate_required_attributes(config, [:user_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_on_call_user_notification_channel('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_on_call_user_notification_channel)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_on_call_user_notification_channel('test', required_attrs)

        expect(ref.id).to eq("${datadog_on_call_user_notification_channel.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ email: { 'key1' => 'val1' }, phone: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_user_notification_channel('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_on_call_user_notification_channel', 'full')
        expect(config).to have_key('email')
        expect(config).to have_key('phone')
      end
    end

    context 'optional attributes' do
      it 'includes email when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_user_notification_channel('opt', required_attrs.merge(email: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_on_call_user_notification_channel', 'opt')
        expect(config).to have_key('email')
      end

      it 'omits email when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_user_notification_channel('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_on_call_user_notification_channel', 'minimal')
        expect(config).not_to have_key('email')
      end
      it 'includes phone when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_user_notification_channel('opt', required_attrs.merge(phone: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_on_call_user_notification_channel', 'opt')
        expect(config).to have_key('phone')
      end

      it 'omits phone when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_user_notification_channel('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_on_call_user_notification_channel', 'minimal')
        expect(config).not_to have_key('phone')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_user_notification_channel('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_on_call_user_notification_channel', 'typed')
        expect(config['user_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_on_call_user_notification_channel('first', required_attrs)
        synth.datadog_on_call_user_notification_channel('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_on_call_user_notification_channel')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_on_call_user_notification_channel,
    method: :datadog_on_call_user_notification_channel,
    required_attrs: { user_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
