# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_security_monitoring_suppression resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogSecurityMonitoringSuppression do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { enabled: true, name: 'test-value', rule_query: 'test-value' } }

  describe ':datadog_security_monitoring_suppression' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'test')
        validate_required_attributes(config, [:enabled, :name, :rule_query])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_security_monitoring_suppression('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_security_monitoring_suppression)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_security_monitoring_suppression('test', required_attrs)

        expect(ref.id).to eq("${datadog_security_monitoring_suppression.test.id}")
        expect(ref.validate).to eq("${datadog_security_monitoring_suppression.test.validate}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'test')
        expect(config).not_to have_key('validate')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ data_exclusion_query: 'test-value', description: 'test-value', expiration_date: 'test-value', start_date: 'test-value', suppression_query: 'test-value', tags: ['test-value'], validate: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'full')
        expect(config).to have_key('data_exclusion_query')
        expect(config).to have_key('description')
        expect(config).to have_key('expiration_date')
        expect(config).to have_key('start_date')
        expect(config).to have_key('suppression_query')
        expect(config).to have_key('tags')
        expect(config).to have_key('validate')
      end
    end

    context 'optional attributes' do
      it 'includes data_exclusion_query when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('opt', required_attrs.merge(data_exclusion_query: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'opt')
        expect(config).to have_key('data_exclusion_query')
      end

      it 'omits data_exclusion_query when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'minimal')
        expect(config).not_to have_key('data_exclusion_query')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes expiration_date when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('opt', required_attrs.merge(expiration_date: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'opt')
        expect(config).to have_key('expiration_date')
      end

      it 'omits expiration_date when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'minimal')
        expect(config).not_to have_key('expiration_date')
      end
      it 'includes start_date when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('opt', required_attrs.merge(start_date: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'opt')
        expect(config).to have_key('start_date')
      end

      it 'omits start_date when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'minimal')
        expect(config).not_to have_key('start_date')
      end
      it 'includes suppression_query when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('opt', required_attrs.merge(suppression_query: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'opt')
        expect(config).to have_key('suppression_query')
      end

      it 'omits suppression_query when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'minimal')
        expect(config).not_to have_key('suppression_query')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes validate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('opt', required_attrs.merge(validate: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'opt')
        expect(config).to have_key('validate')
      end

      it 'omits validate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'minimal')
        expect(config).not_to have_key('validate')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.datadog_security_monitoring_suppression("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts validate=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(validate: val)
          synth.datadog_security_monitoring_suppression("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', "bool_#{val}")
          expect(config['validate']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_security_monitoring_suppression', 'typed')
        expect([true, false]).to include(config['enabled'])
        expect(config['name']).to be_a(String)
        expect(config['rule_query']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_security_monitoring_suppression('first', required_attrs)
        synth.datadog_security_monitoring_suppression('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_security_monitoring_suppression')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_security_monitoring_suppression,
    method: :datadog_security_monitoring_suppression,
    required_attrs: { enabled: true, name: 'test-value', rule_query: 'test-value' },
    expected_outputs: [:id, :validate],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled, :validate]
end
