# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_workflow_automation resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogWorkflowAutomation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { description: 'test-value', name: 'test-value', published: true, spec_json: 'test-value', tags: ['test-value'] } }

  describe ':datadog_workflow_automation' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_workflow_automation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_workflow_automation', 'test')
        validate_required_attributes(config, [:description, :name, :published, :spec_json, :tags])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_workflow_automation('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_workflow_automation)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_workflow_automation('test', required_attrs)

        expect(ref.id).to eq("${datadog_workflow_automation.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ webhook_secret: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_workflow_automation('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_workflow_automation', 'full')
        expect(config).to have_key('webhook_secret')
      end
    end

    context 'optional attributes' do
      it 'includes webhook_secret when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_workflow_automation('opt', required_attrs.merge(webhook_secret: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_workflow_automation', 'opt')
        expect(config).to have_key('webhook_secret')
      end

      it 'omits webhook_secret when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_workflow_automation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_workflow_automation', 'minimal')
        expect(config).not_to have_key('webhook_secret')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:webhook_secret]
        expect(sensitive_fields).to include(:webhook_secret)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts published=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(published: val)
          synth.datadog_workflow_automation("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'datadog_workflow_automation', "bool_#{val}")
          expect(config['published']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_workflow_automation('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_workflow_automation', 'typed')
        expect(config['description']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect([true, false]).to include(config['published'])
        expect(config['spec_json']).to be_a(String)
        expect(config['tags']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_workflow_automation('first', required_attrs)
        synth.datadog_workflow_automation('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_workflow_automation')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_workflow_automation,
    method: :datadog_workflow_automation,
    required_attrs: { description: 'test-value', name: 'test-value', published: true, spec_json: 'test-value', tags: ['test-value'] },
    expected_outputs: [:id],
    sensitive_fields: [:webhook_secret],
    immutable_fields: [],
    boolean_fields: [:published]
end
