# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a datadog_reference_table resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::DatadogReferenceTable do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { source: 'test-value', table_name: 'test-value' } }

  describe ':datadog_reference_table' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'datadog_reference_table', 'test')
        validate_required_attributes(config, [:source, :table_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_reference_table('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:datadog_reference_table)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.datadog_reference_table('test', required_attrs)

        expect(ref.id).to eq("${datadog_reference_table.test.id}")
        expect(ref.created_by).to eq("${datadog_reference_table.test.created_by}")
        expect(ref.last_updated_by).to eq("${datadog_reference_table.test.last_updated_by}")
        expect(ref.row_count).to eq("${datadog_reference_table.test.row_count}")
        expect(ref.status).to eq("${datadog_reference_table.test.status}")
        expect(ref.updated_at).to eq("${datadog_reference_table.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_reference_table', 'test')
        expect(config).not_to have_key('created_by')
        expect(config).not_to have_key('last_updated_by')
        expect(config).not_to have_key('row_count')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', file_metadata: { 'key1' => 'val1' }, schema: { 'key1' => 'val1' }, tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_reference_table', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('file_metadata')
        expect(config).to have_key('schema')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_reference_table', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_reference_table', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes file_metadata when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('opt', required_attrs.merge(file_metadata: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_reference_table', 'opt')
        expect(config).to have_key('file_metadata')
      end

      it 'omits file_metadata when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_reference_table', 'minimal')
        expect(config).not_to have_key('file_metadata')
      end
      it 'includes schema when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('opt', required_attrs.merge(schema: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_reference_table', 'opt')
        expect(config).to have_key('schema')
      end

      it 'omits schema when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_reference_table', 'minimal')
        expect(config).not_to have_key('schema')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_reference_table', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'datadog_reference_table', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'datadog_reference_table', 'typed')
        expect(config['source']).to be_a(String)
        expect(config['table_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.datadog_reference_table('first', required_attrs)
        synth.datadog_reference_table('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'datadog_reference_table')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :datadog_reference_table,
    method: :datadog_reference_table,
    required_attrs: { source: 'test-value', table_name: 'test-value' },
    expected_outputs: [:id, :created_by, :last_updated_by, :row_count, :status, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
